"""
This type stub file was generated by pyright.
"""

import collections.abc
from pathlib import Path
from typing import Callable, List, TYPE_CHECKING, Tuple, Union
from asyncua.ua.uaprotocol_auto import DataTypeAttributes, ObjectAttributes, ObjectTypeAttributes, ReferenceTypeAttributes, VariableAttributes, VariableTypeAttributes
from asyncua import ua
from asyncua.crypto.permission_rules import User

if TYPE_CHECKING:
    __TYPE_ATTRIBUTES = Union[DataTypeAttributes, ReferenceTypeAttributes, VariableTypeAttributes, VariableAttributes, ObjectTypeAttributes, ObjectAttributes,]
_logger = ...
class AttributeValue:
    """
    The class holds the value(s) of an attribute and callbacks.
    """
    def __init__(self, value: ua.DataValue) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class NodeData:
    """
    The class is internal to asyncua and holds all the information about a Node.
    """
    def __init__(self, nodeid: ua.NodeId) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class AttributeService:
    """
    This class implements the attribute service set defined in the opc ua standard.
    https://reference.opcfoundation.org/v104/Core/docs/Part4/5.10.1/
    """
    def __init__(self, aspace: AddressSpace) -> None:
        ...
    
    def read(self, params: ua.ReadParameters) -> List[ua.DataValue]:
        ...
    
    async def write(self, params: ua.WriteParameters, user: User = ...) -> List[ua.StatusCode]:
        ...
    


class ViewService:
    """
    This class implements the view service set defined in the opc ua standard.
    https://reference.opcfoundation.org/v104/Core/docs/Part4/5.8.1/
    """
    def __init__(self, aspace: AddressSpace) -> None:
        ...
    
    def browse(self, params: ua.BrowseParameters) -> List[ua.BrowseResult]:
        ...
    
    def translate_browsepaths_to_nodeids(self, browsepaths: List[ua.BrowsePath]) -> List[ua.BrowsePathResult]:
        ...
    


class NodeManagementService:
    """
    This class implements the node management service set defined in the opc ua standard.
    https://reference.opcfoundation.org/v105/Core/docs/Part4/5.7.1/
    """
    def __init__(self, aspace: AddressSpace) -> None:
        ...
    
    def add_nodes(self, addnodeitems: List[ua.AddNodesItem], user: User = ...) -> List[ua.AddNodesResult]:
        ...
    
    def try_add_nodes(self, addnodeitems: List[ua.AddNodesItem], user: User = ..., check: bool = ...): # -> Generator[AddNodesItem, Any, None]:
        ...
    
    def delete_nodes(self, deletenodeitems: ua.DeleteNodesParameters, user: User = ...) -> List[ua.StatusCode]:
        ...
    
    def add_references(self, refs: List[ua.AddReferencesItem], user: User = ...): # -> list[StatusCode]:
        ...
    
    def try_add_references(self, refs: List[ua.AddReferencesItem], user: User = ...): # -> Generator[AddReferencesItem, Any, None]:
        ...
    
    def delete_references(self, refs: List[ua.DeleteReferencesItem], user: User = ...) -> List[ua.StatusCode]:
        ...
    


class MethodService:
    """
    This class implements the method service set defined in the opc ua standard.
    https://reference.opcfoundation.org/v104/Core/docs/Part4/5.11.1/
    """
    def __init__(self, aspace: AddressSpace) -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    async def call(self, methods): # -> list[Any]:
        ...
    


class AddressSpace:
    """
    The address space object stores all the nodes of the OPC-UA server and helper methods.
    The methods are thread safe

    https://reference.opcfoundation.org/Core/docs/Part3/
    """
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, nodeid: ua.NodeId) -> NodeData:
        ...
    
    def get(self, nodeid: ua.NodeId) -> Union[NodeData, None]:
        ...
    
    def __setitem__(self, nodeid: ua.NodeId, value: NodeData): # -> None:
        ...
    
    def __contains__(self, nodeid: ua.NodeId) -> bool:
        ...
    
    def __delitem__(self, nodeid: ua.NodeId): # -> None:
        ...
    
    def generate_nodeid(self, idx: Union[int, None] = ...) -> ua.NodeId:
        ...
    
    def keys(self): # -> dict_keys[NodeId, NodeData]:
        ...
    
    def clear(self): # -> None:
        """Delete all nodes in address space"""
        ...
    
    def dump(self, path): # -> None:
        """
        Dump address space as binary to file; note that server must be stopped for this method to work
        DO NOT DUMP AN ADDRESS SPACE WHICH IS USING A SHELF (load_aspace_shelf), ONLY CACHED NODES WILL GET DUMPED!
        """
        ...
    
    def load(self, path): # -> None:
        """
        Load address space from a binary file, overwriting everything in the current address space
        """
        ...
    
    def make_aspace_shelf(self, path: Path): # -> None:
        """
        Make a shelf for containing the nodes from the standard address space; this is typically only done on first
        start of the server. Subsequent server starts will load the shelf, nodes are then moved to a cache
        by the LazyLoadingDict class when they are accessed. Saving data back to the shelf
        is currently NOT supported, it is only used for the default OPC UA standard address space

        Note: Intended for slow devices, such as Raspberry Pi, to greatly improve start up time
        """
        ...
    
    def load_aspace_shelf(self, path: Path): # -> None:
        """
        Load the standard address space nodes from a python shelve via LazyLoadingDict as needed.
        The dump() method can no longer be used if the address space is being loaded from a shelf

        Note: Intended for slow devices, such as Raspberry Pi, to greatly improve start up time
        """
        class LazyLoadingDict(collections.abc.MutableMapping):
            """
            Special dict that only loads nodes as they are accessed. If a node is accessed it gets copied from the
            shelf to the cache dict. All user nodes are saved in the cache ONLY. Saving data back to the shelf
            is currently NOT supported
            """
            ...
        
        
    
    def read_attribute_value(self, nodeid: ua.NodeId, attr: ua.AttributeIds) -> ua.DataValue:
        ...
    
    async def write_attribute_value(self, nodeid: ua.NodeId, attr: ua.AttributeIds, value: ua.DataValue) -> ua.StatusCode:
        ...
    
    def set_attribute_value_callback(self, nodeid: ua.NodeId, attr: ua.AttributeIds, callback: Callable[[ua.NodeId, ua.AttributeIds], ua.DataValue]) -> ua.StatusCode:
        ...
    
    def set_attribute_value_setter(self, nodeid: ua.NodeId, attr: ua.AttributeIds, setter: Callable[[NodeData, ua.AttributeIds], ua.DataValue]) -> ua.StatusCode:
        ...
    
    def add_datachange_callback(self, nodeid: ua.NodeId, attr: ua.AttributeIds, callback: Callable) -> Tuple[ua.StatusCode, int]:
        ...
    
    def delete_datachange_callback(self, handle: int): # -> None:
        ...
    
    def add_method_callback(self, methodid: ua.NodeId, callback: Callable): # -> None:
        ...
    


