"""
This type stub file was generated by pyright.
"""

import asyncio
from ..common.connection import TransportLimits
from .internal_server import InternalServer

"""
Socket server forwarding request to internal server
"""
_logger = ...
class OPCUAProtocol(asyncio.Protocol):
    """
    Instantiated for every connection.
    """
    def __init__(self, iserver: InternalServer, policies, clients, closing_tasks, limits: TransportLimits) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def connection_made(self, transport): # -> None:
        ...
    
    def connection_lost(self, ex): # -> None:
        ...
    
    def data_received(self, data): # -> None:
        ...
    


class BinaryServer:
    def __init__(self, internal_server: InternalServer, hostname, port, limits: TransportLimits) -> None:
        ...
    
    def set_policies(self, policies): # -> None:
        ...
    
    async def start(self): # -> None:
        ...
    
    async def stop(self): # -> None:
        ...
    


