"""
This type stub file was generated by pyright.
"""

from asyncua.server.internal_session import InternalSession

class EventGenerator:
    """
    Create an event based on an event type. Per default is BaseEventType used.
    Object members are dynamically created from the base event type and send to
    client when evebt is triggered (see example code in source)

    Arguments to constructor are:
        server: The InternalSession object to use for query and event triggering
        source: The emiting source for the node, either an objectId, NodeId or a Node
        etype: The event type, either an objectId, a NodeId or a Node object
    """
    def __init__(self, isession: InternalSession) -> None:
        ...
    
    async def init(self, etype=..., emitting_node=..., add_generates_event=...): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    async def trigger(self, time_attr=..., message=..., subscription_id=...): # -> None:
        """
        Trigger the event. This will send a notification to all subscribed clients
        """
        ...
    


