"""
This type stub file was generated by pyright.
"""

from asyncua import ua

_logger = ...
class UaNodeAlreadyHistorizedError(ua.UaError):
    ...


class HistoryStorageInterface:
    """
    Interface of a history backend.
    Must be implemented by backends
    """
    def __init__(self, max_history_data_response_size=...) -> None:
        ...
    
    async def init(self):
        """
        Async. initialization.
        Has to be called once after creation.
        """
        ...
    
    async def new_historized_node(self, node_id, period, count=...):
        """
        Called when a new node is to be historized
        Returns None
        """
        ...
    
    async def save_node_value(self, node_id, datavalue):
        """
        Called when the value of a historized node has changed and should be saved in history
        Returns None
        """
        ...
    
    async def read_node_history(self, node_id, start, end, nb_values):
        """
        Called when a client make a history read request for a node
        if start or end is missing then nb_values is used to limit query
        nb_values is the max number of values to read. Ignored if 0
        Start time and end time are inclusive
        Returns a list of DataValues and a continuation point which
        is None if all nodes are read or the SourceTimeStamp of the last rejected DataValue
        """
        ...
    
    async def new_historized_event(self, source_id, evtypes, period, count=...):
        """
        Called when historization of events is enabled on server side
        Returns None
        """
        ...
    
    async def save_event(self, event):
        """
        Called when a new event has been generated ans should be saved in history
        Returns None
        """
        ...
    
    async def read_event_history(self, source_id, start, end, nb_values, evfilter):
        """
        Called when a client make a history read request for events
        Start time and end time are inclusive
        Returns a list of Events and a continuation point which
        is None if all events are read or the SourceTimeStamp of the last rejected event
        """
        ...
    
    async def stop(self):
        """
        Called when the server shuts down
        Can be used to close database connections etc.
        """
        ...
    


class HistoryDict(HistoryStorageInterface):
    """
    Very minimal history backend storing data in memory using a Python dictionary
    """
    def __init__(self, max_history_data_response_size=...) -> None:
        ...
    
    async def init(self): # -> None:
        ...
    
    async def new_historized_node(self, node_id, period, count=...): # -> None:
        ...
    
    async def save_node_value(self, node_id, datavalue): # -> None:
        ...
    
    async def read_node_history(self, node_id, start, end, nb_values): # -> tuple[list[Any], None] | tuple[list[Any], Any | None]:
        ...
    
    async def new_historized_event(self, source_id, evtypes, period, count=...): # -> None:
        ...
    
    async def save_event(self, event): # -> None:
        ...
    
    async def read_event_history(self, source_id, start, end, nb_values, evfilter): # -> tuple[list[Any], None] | tuple[list[Any], Any | None]:
        ...
    
    async def stop(self): # -> None:
        ...
    


class SubHandler:
    def __init__(self, storage: HistoryStorageInterface) -> None:
        ...
    
    def datachange_notification(self, node, val, data): # -> None:
        ...
    
    def event_notification(self, event): # -> None:
        ...
    


class HistoryManager:
    def __init__(self, iserver) -> None:
        ...
    
    async def init(self): # -> None:
        ...
    
    def set_storage(self, storage): # -> None:
        """
        set the desired HistoryStorageInterface which History Manager will use for historizing
        """
        ...
    
    async def historize_data_change(self, node, period=..., count=...): # -> None:
        """
        Subscribe to the nodes' data changes and store the data in the active storage.
        """
        ...
    
    async def historize_event(self, source, period=..., count=...): # -> None:
        """
        Subscribe to the source nodes' events and store the data in the active storage.

        SQL Implementation
        The default is to historize every event type the source generates,
        custom event properties are included. At
        this time there is no way to historize a specific event type. The user software can filter
        out events which are not desired when reading.

        Note that adding custom events to a source node AFTER historizing has been activated is not
        supported at this time (in SQL history there will be no columns in the SQL table for the new
        event properties). For SQL The table
        must be deleted manually so that a new table with the custom event fields can be created.
        """
        ...
    
    async def dehistorize(self, node): # -> None:
        """
        Remove subscription to the node/source which is being historized

        SQL Implementation
        Only the subscriptions is removed. The historical data remains.
        """
        ...
    
    async def read_history(self, params): # -> list[Any]:
        """
        Read history for a node
        This is the part AttributeService, but implemented as its own service
        since it requires more logic than other attribute service methods
        """
        ...
    
    def update_history(self, params): # -> list[Any]:
        """
        Update history for a node
        This is the part AttributeService, but implemented as its own service
        since it requires more logic than other attribute service methods
        """
        ...
    
    async def stop(self): # -> None:
        """
        call stop methods of active storage interface whenever the server is stopped
        """
        ...
    


