"""
This type stub file was generated by pyright.
"""

from typing import Iterable
from asyncua import ua
from .address_space import AddressSpace

"""
server side implementation of a subscription object
"""
class InternalSubscription:
    """
    Server internal subscription.
    Runs the publication loop and stores the Publication Results until they are acknowledged.
    """
    def __init__(self, data: ua.CreateSubscriptionResult, aspace: AddressSpace, callback, session_id, request_callback=..., delete_callback=...) -> None:
        """
        :param loop: Event loop instance
        :param data: Create Subscription Result
        :param aspace: Server Address Space
        :param callback: Callback for publishing
        :param session_id: Id of the session that owns this subscription.
        :param request_callback: Callback for getting queued publish requests.
            If None, publishing will be done without waiting for a token and no
            acknowledging will be expected (for server internal subscriptions)
        :param delete_callback: Optional callback to call when the subscription
            is stopped due to the publish count exceeding the
            RevisedLifetimeCount.
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    async def start(self): # -> None:
        ...
    
    async def stop(self): # -> None:
        ...
    
    def has_published_results(self): # -> bool:
        ...
    
    async def publish_results(self, requestdata=...): # -> bool:
        """
        Publish all enqueued data changes, events and status changes though the callback.
        This method gets first called without publish request from subscription loop.
        It tries to get a publish request itself (if needed). If it doesn't succeed, method gets
        queued to be called back with publish request when one is available.
        """
        ...
    
    def publish(self, acks: Iterable[int]): # -> None:
        """
        Reset publish cycle count, acknowledge PublishResults.
        :param acks: Sequence number of the PublishResults to acknowledge
        """
        ...
    
    def republish(self, nb): # -> NotificationMessage:
        ...
    
    async def enqueue_datachange_event(self, mid: int, eventdata: ua.MonitoredItemNotification, maxsize: int): # -> None:
        """
        Enqueue a monitored item data change.
        :param mid: Monitored Item Id
        :param eventdata: Monitored Item Notification
        :param maxsize: Max queue size (0: No limit)
        """
        ...
    
    async def enqueue_event(self, mid: int, eventdata: ua.EventFieldList, maxsize: int): # -> None:
        """
        Enqueue a event.
        :param mid: Monitored Item Id
        :param eventdata: Event Field List
        :param maxsize: Max queue size (0: No limit)
        """
        ...
    
    async def enqueue_statuschange(self, code): # -> None:
        """
        Enqueue a status change.
        :param code:
        """
        ...
    


