"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional
from pathlib import Path
from asyncua import ua
from .user_managers import UserManager
from .address_space import NodeData

"""
Internal server implementing opcu-ua interface.
Can be used on server side or to implement binary/https opc-ua servers
"""
_logger = ...
class ServerDesc:
    def __init__(self, serv, cap=...) -> None:
        ...
    


class InternalServer:
    """
    There is one `InternalServer` for every `Server`.
    """
    def __init__(self, user_manager: UserManager = ...) -> None:
        ...
    
    async def init(self, shelffile: Optional[Path] = ...): # -> None:
        ...
    
    async def setup_condition_methods(self): # -> None:
        ...
    
    async def setup_nodes(self): # -> None:
        """
        Set up some nodes as defined by spec
        """
        ...
    
    async def load_standard_address_space(self, shelf_file: Optional[Path] = ...): # -> None:
        ...
    
    def load_address_space(self, path): # -> None:
        """
        Load address space from path
        """
        ...
    
    def dump_address_space(self, path): # -> None:
        """
        Dump current address space to path
        """
        ...
    
    async def start(self): # -> None:
        ...
    
    async def stop(self): # -> None:
        ...
    
    def get_new_channel_id(self): # -> int:
        ...
    
    def add_endpoint(self, endpoint): # -> None:
        ...
    
    async def get_endpoints(self, params=..., sockname=...): # -> list[Any]:
        ...
    
    def find_servers(self, params, sockname=...): # -> list[Any]:
        ...
    
    def register_server(self, server, conf=...): # -> None:
        ...
    
    def register_server2(self, params): # -> None:
        ...
    
    def create_session(self, name, user=..., external=...): # -> InternalSession:
        ...
    
    async def enable_history_data_change(self, node, period=..., count=...): # -> None:
        """
        Set attribute Historizing of node to True and start storing data for history
        """
        ...
    
    async def disable_history_data_change(self, node): # -> None:
        """
        Set attribute Historizing of node to False and stop storing data for history
        """
        ...
    
    async def enable_history_event(self, source, period=..., count=...): # -> None:
        """
        Set attribute History Read of object events to True and start storing data for history
        """
        ...
    
    async def disable_history_event(self, source): # -> None:
        """
        Set attribute History Read of node to False and stop storing data for history
        """
        ...
    
    def subscribe_server_callback(self, event, handle): # -> None:
        """
        Create a subscription from event to handle
        """
        ...
    
    def unsubscribe_server_callback(self, event, handle): # -> None:
        """
        Remove a subscription from event to handle
        """
        ...
    
    async def write_attribute_value(self, nodeid, datavalue, attr=...): # -> None:
        """
        directly write datavalue to the Attribute, bypassing some checks and structure creation,
        so it is a little faster
        """
        ...
    
    def set_attribute_value_callback(self, nodeid: ua.NodeId, callback: Callable[[ua.NodeId, ua.AttributeIds], ua.DataValue], attr=...) -> None:
        """
        Set a callback function to the Attribute that returns a value for read_attribute_value() instead of the
        written value. Note that it does not trigger the datachange_callbacks unlike write_attribute_value().
        """
        ...
    
    def set_attribute_value_setter(self, nodeid: ua.NodeId, setter: Callable[[NodeData, ua.AttributeIds, ua.DataValue], None], attr=...) -> None:
        """
        Set a setter function for the Attribute. This setter will be called when a new value is set using
        write_attribute_value() instead of directly writing the value. This is useful, for example, if you want to
        intercept writes to certain attributes to perform some kind of validation of the value to be written and return
        appropriate status codes to the client.
        """
        ...
    
    def read_attribute_value(self, nodeid, attr=...): # -> DataValue:
        """
        directly read datavalue of the Attribute
        """
        ...
    
    def set_user_manager(self, user_manager): # -> None:
        """
        set up a function which that will check for authorize users. Input function takes username
        and password as parameters and returns True of user is allowed access, False otherwise.
        """
        ...
    
    def decrypt_user_token(self, isession, token): # -> tuple[Any, Any | str]:
        """
        unpack the username and password for the benefit of the user defined user manager
        """
        ...
    
    def verify_x509_token(self, isession, token, signature):
        """
        verify certificate signature
        """
        ...
    


