"""
This type stub file was generated by pyright.
"""

from asyncua import ua
from typing import Optional
from .address_space import AddressSpace

"""
server side implementation of a subscription object
"""
class MonitoredItemData:
    def __init__(self) -> None:
        ...
    


class MonitoredItemValues:
    def __init__(self) -> None:
        ...
    
    def set_current_datavalue(self, cur_val: ua.DataValue): # -> None:
        ...
    
    def get_current_datavalue(self) -> Optional[ua.DataValue]:
        ...
    
    def get_old_datavalue(self) -> Optional[ua.DataValue]:
        ...
    


class MonitoredItemService:
    """
    Implements monitored item service for one subscription
    """
    def __init__(self, isub, aspace: AddressSpace) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def delete_all_monitored_items(self): # -> None:
        ...
    
    async def create_monitored_items(self, params: ua.CreateMonitoredItemsParameters): # -> list[Any]:
        ...
    
    def modify_monitored_items(self, params: ua.ModifyMonitoredItemsParameters): # -> list[Any]:
        ...
    
    async def trigger_datachange(self, handle, nodeid, attr): # -> None:
        ...
    
    def delete_monitored_items(self, ids): # -> list[Any]:
        ...
    
    async def datachange_callback(self, handle: int, value: ua.DataValue, error=...): # -> None:
        ...
    
    async def trigger_event(self, event, mid=...): # -> bool:
        ...
    
    async def trigger_statuschange(self, code): # -> None:
        ...
    


class WhereClauseEvaluator:
    def __init__(self, logger, aspace: AddressSpace, whereclause) -> None:
        ...
    
    def eval(self, event): # -> bool:
        ...
    


