"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional, Union
from pathlib import Path
from asyncua import ua
from .address_space import NodeData
from .internal_server import InternalServer
from ..common.node import Node
from ..crypto import validator

"""
High level interface to pure python OPC-UA server
"""
_logger = ...
class Server:
    """
    High level Server class

    This class creates an asyncua server with default values

    Create your own namespace and then populate your server address space
    using use the get_root() or get_objects() to get Node objects.
    and get_event_object() to fire events.
    Then start server. See server-example.py
    All methods are threadsafe

    If you need more flexibility you call directly the Ua Service methods
    on the iserver or iserver.isession object members.

    During startup the standard address space will be constructed, which may be
    time-consuming when running a server on a less powerful device (e.g. a
    Raspberry Pi). In order to improve startup performance, an optional path to a
    cache file can be passed to the server constructor.
    If the parameter is defined, the address space will be loaded from the
    cache file or the file will be created if it does not exist yet.
    As a result the first startup will be even slower due to the cache file
    generation but all further start ups will be significantly faster.
    ┌────────┐
    │ Server │ ── BinaryServer ── OPCUAProtocol ── UaProcessor
    │        │ ── InternalServer ── InternalSession
    └────────┘                   ── SubscriptionService

    :ivar product_uri:
    :ivar name:
    :ivar default_timeout: timeout in milliseconds for sessions and secure channel
    :ivar iserver: `InternalServer` instance
    :ivar bserver: binary protocol server `BinaryServer`
    :ivar nodes: shortcuts to common nodes - `Shortcuts` instance
    :ivar socket_address:
        A tuple of IP address and port describing the server socket address. Used when the IP address of the network
        interface is different from the endpoint IP offered to the client during discovery. Helpful when the server
        is running behind NAT or inside a Docker container, where the client connects to an external IP, while the
        server listens on some internal IP.
    """
    def __init__(self, iserver: InternalServer = ..., user_manager=...) -> None:
        ...
    
    async def init(self, shelf_file: Optional[Path] = ...): # -> None:
        ...
    
    def set_match_discovery_endpoint_url(self, match_discovery_endpoint_url: bool): # -> None:
        """
        Enables or disables the matching of the EndpointUrl request parameter during discovery.

        When True (default), the host/port of endpoints sent during the discovery is modified to the host/port
        which is specified in the EndpointUrl request parameter.
        """
        ...
    
    def set_match_discovery_client_ip(self, match_discovery_client_ip: bool): # -> None:
        """
        Enables or disables the matching of an endpoint IP to a client IP during discovery.

        When True (default), the IP address of endpoints sent during the discovery is modified to an IP address
        of the server network interface used to communicate with the client. Disabling comes handy when the real
        client IP is different from the client IP that the server sees (e.g., behind NAT or inside Docker container).
        Do not call unless you know what you are doing.
        """
        ...
    
    def set_force_server_timestamp(self, force_server_timestamp: bool): # -> None:
        """
        Enables or disables automatically setting ServerTimestamp on Value attributes
        """
        ...
    
    async def set_build_info(self, product_uri, manufacturer_name, product_name, software_version, build_number, build_date): # -> None:
        ...
    
    async def __aenter__(self): # -> None:
        ...
    
    async def __aexit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    async def load_certificate(self, path_or_content: Union[str, bytes, Path], format: str = ...): # -> None:
        """
        load server certificate from file, either pem or der
        """
        ...
    
    async def load_private_key(self, path_or_content: Union[str, Path, bytes], password=..., format=...): # -> None:
        ...
    
    def disable_clock(self, val: bool = ...): # -> None:
        """
        for debugging you may want to disable clock that write every second
        to address space
        """
        ...
    
    def get_application_uri(self): # -> str:
        ...
    
    async def set_application_uri(self, uri: str): # -> None:
        """
        Set application/server URI.
        This uri is supposed to be unique. If you intend to register
        your server to a discovery server, it really should be unique in
        your system!
        default is : "urn:freeopcua:python:server"
        """
        ...
    
    async def find_servers(self, uris=...): # -> list[Any]:
        """
        find_servers. mainly implemented for symmetry with client
        """
        ...
    
    async def register_to_discovery(self, url: str = ..., period: int = ..., discovery_configuration=...): # -> None:
        """
        Register to an OPC-UA Discovery server. Registering must be renewed at
        least every 10 minutes, so this method will use our asyncio thread to
        re-register every period seconds
        if period is 0 registration is not automatically renewed
        """
        ...
    
    async def unregister_from_discovery(self, url: str = ..., discovery_configuration=...): # -> None:
        """
        stop registration thread
        """
        ...
    
    def allow_remote_admin(self, allow): # -> None:
        """
        Enable or disable the builtin Admin user from network clients
        """
        ...
    
    def set_endpoint(self, url): # -> None:
        ...
    
    async def get_endpoints(self): # -> list[Any]:
        ...
    
    def set_security_policy(self, security_policy, permission_ruleset=...): # -> None:
        """
        Method setting up the security policies for connections
        to the server, where security_policy is a list of integers.
        During server initialization, all endpoints are enabled:

                security_policy = [
                            ua.SecurityPolicyType.NoSecurity,
                            ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt,
                            ua.SecurityPolicyType.Basic256Sha256_Sign
                                ]

        E.g. to limit the number of endpoints and disable no encryption:

                set_security_policy([
                            ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt])

        """
        ...
    
    def set_security_IDs(self, policy_ids): # -> None:
        """
        DEPRECATED!
        Only available for backwards compatibility.
        Use set_identity_tokens instead.
        """
        ...
    
    def set_identity_tokens(self, tokens): # -> None:
        """
        Method setting up allowed identity token types for authentication.

        E.g. to disable anonymous clients:

            set_identity_tokens([ua.X509IdentityToken, ua.UserNameIdentityToken])
        """
        ...
    
    def set_server_name(self, name): # -> None:
        ...
    
    async def start(self): # -> None:
        """
        Start to listen on network
        """
        ...
    
    async def stop(self): # -> None:
        """
        Stop server
        """
        ...
    
    def get_root_node(self): # -> Node:
        """
        Get Root node of server. Returns a Node object.
        """
        ...
    
    def get_objects_node(self): # -> Node:
        """
        Get Objects node of server. Returns a Node object.
        """
        ...
    
    def get_node(self, nodeid: Union[Node, ua.NodeId, str, int]) -> Node:
        """
        Get a specific node using NodeId object or a string representing a NodeId
        """
        ...
    
    async def create_subscription(self, period, handler): # -> Subscription:
        """
        Create a subscription.
        Returns a Subscription object which allow to subscribe to events or data changes on server
        :param period: Period in milliseconds
        :param handler: A class instance - see `SubHandler` base class for details
        """
        ...
    
    async def get_namespace_array(self): # -> Any:
        """
        get all namespace defined in server
        """
        ...
    
    async def register_namespace(self, uri) -> int:
        """
        Register a new namespace. Nodes should in custom namespace, not 0.
        """
        ...
    
    async def get_namespace_index(self, uri): # -> Any:
        """
        get index of a namespace using its uri
        """
        ...
    
    async def get_event_generator(self, etype=..., emitting_node=...): # -> EventGenerator:
        """
        Returns an event object using an event type from address space.
        Use this object to fire events
        """
        ...
    
    async def create_custom_data_type(self, idx, name, basetype=..., properties=..., description=...): # -> Node:
        ...
    
    async def create_custom_event_type(self, idx, name, basetype=..., properties=...): # -> Node:
        ...
    
    async def create_custom_object_type(self, idx, name, basetype=..., properties=..., variables=..., methods=...): # -> Node:
        ...
    
    async def create_custom_variable_type(self, idx, name, basetype=..., properties=..., variables=..., methods=...): # -> Node:
        ...
    
    async def import_xml(self, path=..., xmlstring=..., strict_mode=..., auto_load_definitions: bool = ...): # -> list[Any]:
        """
        Import nodes defined in xml
        """
        ...
    
    async def export_xml(self, nodes, path, export_values: bool = ...): # -> None:
        """
        Export defined nodes to xml
        :param export_value: export values from variants
        """
        ...
    
    async def export_xml_by_ns(self, path: str, namespaces: list = ..., export_values: bool = ...): # -> None:
        """
        Export nodes of one or more namespaces to an XML file.
        Namespaces used by nodes are always exported for consistency.
        :param path: name of the xml file to write
        :param namespaces: list of string uris or int indexes of the namespace to export,
        :param export_values: export values from variants
         if not provide all ns are used except 0
        """
        ...
    
    async def delete_nodes(self, nodes, recursive=...): # -> Tuple[List[Node], List[StatusCode]]:
        ...
    
    async def historize_node_data_change(self, node, period=..., count=...): # -> None:
        """
        Start historizing supplied nodes; see history module
        :param node: node or list of nodes that can be historized (variables/properties)
        :param period: time delta to store the history; older data will be deleted from the storage
        :param count: number of changes to store in the history
        """
        ...
    
    async def dehistorize_node_data_change(self, node): # -> None:
        """
        Stop historizing supplied nodes; see history module
        :param node: node or list of nodes that can be historized (UA variables/properties)
        """
        ...
    
    async def historize_node_event(self, node, period=..., count: int = ...): # -> None:
        """
        Start historizing events from node (typically a UA object); see history module
        :param node: node or list of nodes that can be historized (UA objects)
        :param period: time delta to store the history; older data will be deleted from the storage
        :param count: number of events to store in the history
        """
        ...
    
    async def dehistorize_node_event(self, node): # -> None:
        """
        Stop historizing events from node (typically a UA object); see history module
        :param node: node or list of nodes that can be historized (UA objects)
        """
        ...
    
    def subscribe_server_callback(self, event, handle): # -> None:
        ...
    
    def unsubscribe_server_callback(self, event, handle): # -> None:
        ...
    
    def link_method(self, node, callback): # -> None:
        """
        Link a python function to a UA method in the address space; required when a UA method has been imported
        to the address space via XML; the python executable must be linked manually
        :param node: UA method node
        :param callback: python function that the UA method will call
        """
        ...
    
    async def load_type_definitions(self, nodes=...): # -> tuple[list[Any], dict[Any, Any]]:
        """
        load custom structures from our server.
        Server side this can be used to create python objects from custom structures
        imported through xml into server
        """
        ...
    
    async def load_data_type_definitions(self, node=...): # -> Dict[Any, Any]:
        """
        Load custom types (custom structures/extension objects) definition from server
        Generate Python classes for custom structures/extension objects defined in server
        These classes will be available in ua module
        """
        ...
    
    async def load_enums(self): # -> dict[str, Any]:
        """
        load UA structures and generate python Enums in ua module for custom enums in server
        """
        ...
    
    async def write_attribute_value(self, nodeid, datavalue, attr=...): # -> None:
        """
        directly write datavalue to the Attribute, bypassing some checks and structure creation,
        so it is a little faster
        """
        ...
    
    def set_attribute_value_callback(self, nodeid: ua.NodeId, callback: Callable[[ua.NodeId, ua.AttributeIds], ua.DataValue], attr=...) -> None:
        """
        Set a callback function to the Attribute that returns a value for read_attribute_value() instead of the
        written value. Note that it does not trigger the datachange_callbacks unlike write_attribute_value().
        """
        ...
    
    def set_attribute_value_setter(self, nodeid: ua.NodeId, setter: Callable[[NodeData, ua.AttributeIds, ua.DataValue], None], attr=...) -> None:
        """
        Set a setter function for the Attribute. This setter will be called when a new value is set using
        write_attribute_value() instead of directly writing the value. This is useful, for example, if you want to
        intercept writes to certain attributes to perform some kind of validation of the value to be written and return
        appropriate status codes to the client.
        """
        ...
    
    def read_attribute_value(self, nodeid, attr=...): # -> DataValue:
        """
        directly read datavalue of the Attribute
        """
        ...
    
    def set_certificate_validator(self, validator: validator.CertificateValidatorMethod): # -> None:
        """
        Assign a method to be called when certificate needs to be validated.

        Function is called with certificate and application description and should raise the correct status code
        when invalid.

            async def example_validation_method(certificate: x509.Certificate, app_description: ua.ApplicationDescription):
                ...
                if not_valid_condition:
                    raise ServiceError(ua.StatusCodes.BadCertificateInvalid)
        """
        ...
    


