"""
This type stub file was generated by pyright.
"""

from typing import Iterable
from asyncua import ua
from asyncua.common import uamethod
from .address_space import AddressSpace

"""
server side implementation of subscription service
"""
class SubscriptionService:
    """
    Manages subscriptions on the server side.
    There is one `SubscriptionService` instance for every `Server`/`InternalServer`.
    """
    def __init__(self, aspace: AddressSpace) -> None:
        ...
    
    async def create_subscription(self, params, callback, session_id, request_callback=...): # -> CreateSubscriptionResult:
        ...
    
    def modify_subscription(self, params): # -> ModifySubscriptionResult:
        ...
    
    async def delete_subscriptions(self, ids): # -> <subclass of list and Exception> | list[Any]:
        ...
    
    def publish(self, acks: Iterable[ua.SubscriptionAcknowledgement]): # -> None:
        ...
    
    async def create_monitored_items(self, params: ua.CreateMonitoredItemsParameters): # -> list[Any]:
        ...
    
    def modify_monitored_items(self, params): # -> list[Any]:
        ...
    
    def delete_monitored_items(self, params): # -> list[Any]:
        ...
    
    def republish(self, params): # -> NotificationMessage:
        ...
    
    async def trigger_event(self, event, subscription_id=...): # -> None:
        ...
    
    @uamethod
    async def condition_refresh(self, parent, subscription_id, mid=...): # -> StatusCode | None:
        ...
    


