"""
This type stub file was generated by pyright.
"""

from asyncua import ua
from .internal_server import InternalServer
from ..common.connection import TransportLimits

_logger = ...
class PublishRequestData:
    def __init__(self, requesthdr=..., seqhdr=...) -> None:
        ...
    


class UaProcessor:
    """
    Processor for OPC UA messages. Implements the OPC UA protocol for the server side.
    """
    def __init__(self, internal_server: InternalServer, transport, limits: TransportLimits) -> None:
        ...
    
    def set_policies(self, policies): # -> None:
        ...
    
    def send_response(self, requesthandle, seqhdr, response, msgtype=...): # -> None:
        ...
    
    def open_secure_channel(self, algohdr, seqhdr, body): # -> None:
        ...
    
    def get_publish_request(self, subscription_id: ua.IntegerId): # -> PublishRequestData | None:
        ...
    
    async def forward_publish_response(self, result: ua.PublishResult, requestdata: PublishRequestData): # -> None:
        """
        Try to send a `PublishResponse` with the given `PublishResult`.
        """
        ...
    
    async def process(self, header, body): # -> bool | None:
        ...
    
    async def process_message(self, seqhdr, body): # -> Literal[True] | None:
        """
        Process incoming messages.
        """
        ...
    
    async def close(self): # -> None:
        """
        to be called when client has disconnected to ensure we really close
        everything we should
        """
        ...
    


