"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Union
from asyncua.crypto.permission_rules import UserRole

class UserManager:
    def get_user(self, iserver, username=..., password=..., certificate=...):
        ...
    


class PermissiveUserManager:
    def get_user(self, iserver, username=..., password=..., certificate=...): # -> User:
        """
        Default user_manager, does nothing much but check for admin
        """
        ...
    


class CertificateUserManager:
    """
    Certificate user manager, takes a certificate handler with its associated users and provides those users.
    """
    def __init__(self) -> None:
        ...
    
    async def add_role(self, certificate_path: Path, user_role: UserRole, name: str, format: Union[str, None] = ...): # -> None:
        ...
    
    def get_user(self, iserver, username=..., password=..., certificate=...): # -> None:
        ...
    
    async def add_user(self, certificate_path: Path, name: str, format: Union[str, None] = ...): # -> None:
        ...
    
    async def add_admin(self, certificate_path: Path, name: str, format: Union[str, None] = ...): # -> None:
        ...
    


