"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""
server side implementation of callback event
"""
class CallbackType(Enum):
    """
    The possible types of a Callback type.

    :ivar Null:
    :ivar MonitoredItem:

    """
    Null = ...
    ItemSubscriptionCreated = ...
    ItemSubscriptionModified = ...
    ItemSubscriptionDeleted = ...
    PreWrite = ...
    PostWrite = ...
    PreRead = ...
    PostRead = ...


class Callback:
    def __init__(self) -> None:
        ...
    
    def setName(self, name): # -> None:
        ...
    
    def getName(self): # -> None:
        ...
    


class ServerItemCallback(Callback):
    def __init__(self, request_params, response_params, user=..., is_external=...) -> None:
        ...
    


class CallbackSubscriberInterface:
    def getSubscribedEvents(self):
        ...
    


class CallbackService:
    def __init__(self) -> None:
        ...
    
    async def dispatch(self, eventName, event=...): # -> Callback:
        ...
    
    async def call_listener(self, event, listener): # -> None:
        ...
    
    def addListener(self, eventName, listener, priority=...): # -> None:
        ...
    
    def removeListener(self, eventName, listener=...): # -> None:
        ...
    
    def addSubscriber(self, subscriber): # -> None:
        ...
    


