"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from asyncua import ua

_logger = ...
@dataclass
class TransportLimits:
    """
    Limits of the tcp transport layer to prevent excessive resource usage
    """
    max_recv_buffer: int = ...
    max_send_buffer: int = ...
    max_chunk_count: int = ...
    max_message_size: int = ...
    def is_msg_size_within_limit(self, sz: int) -> bool:
        ...
    
    def is_chunk_count_within_limit(self, sz: int) -> bool:
        ...
    
    def create_acknowledge_and_set_limits(self, msg: ua.Hello) -> ua.Acknowledge:
        ...
    
    def create_hello_limits(self, msg: ua.Hello) -> ua.Hello:
        ...
    
    def update_client_limits(self, msg: ua.Acknowledge) -> None:
        ...
    


class MessageChunk:
    """
    Message Chunk, as described in OPC UA specs Part 6, 6.7.2.
    """
    def __init__(self, crypto, body=..., msg_type=..., chunk_type=...) -> None:
        ...
    
    @staticmethod
    def from_binary(security_policy, data): # -> MessageChunk:
        ...
    
    @staticmethod
    def from_header_and_body(security_policy, header, buf, use_prev_key=...): # -> MessageChunk:
        ...
    
    def encrypted_size(self, plain_size):
        ...
    
    def to_binary(self):
        ...
    
    @staticmethod
    def max_body_size(crypto, max_chunk_size):
        ...
    
    @staticmethod
    def message_to_chunks(security_policy, body, max_chunk_size, message_type=..., channel_id=..., request_id=..., token_id=...): # -> list[MessageChunk] | list[Any]:
        """
        Pack message body (as binary string) into one or more chunks.
        Size of each chunk will not exceed max_chunk_size.
        Returns a list of MessageChunks. SequenceNumber is not initialized here,
        it must be set by Secure Channel driver.
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class SecureConnection:
    """
    Common logic for client and server
    """
    def __init__(self, security_policy, limits: TransportLimits) -> None:
        ...
    
    def set_channel(self, params, request_type, client_nonce): # -> None:
        """
        Called on client side when getting secure channel data from server.
        """
        ...
    
    def open(self, params, server): # -> OpenSecureChannelResult:
        """
        Called on server side to open secure channel.
        """
        ...
    
    def close(self): # -> None:
        ...
    
    def is_open(self): # -> bool:
        ...
    
    def set_policy_factories(self, policies): # -> None:
        """
        Set a list of available security policies.
        Use this in servers with multiple endpoints with different security.
        """
        ...
    
    def select_policy(self, uri, peer_certificate, mode=...): # -> None:
        ...
    
    def revolve_tokens(self): # -> None:
        """
        Revolve security tokens of the security channel. Start using the
        next security token negotiated during the renewal of the channel and
        remember the previous token until the other communication party
        """
        ...
    
    def message_to_binary(self, message, message_type=..., request_id=...): # -> bytes:
        """
        Convert OPC UA secure message to binary.
        The only supported types are SecureOpen, SecureMessage, SecureClose.
        If message_type is SecureMessage, the AlgorithmHeader should be passed as arg.
        """
        ...
    
    def receive_from_header_and_body(self, header, body): # -> Message | Hello | Acknowledge | ErrorMessage | None:
        """
        Convert MessageHeader and binary body to OPC UA TCP message (see OPC UA
        specs Part 6, 7.1: Hello, Acknowledge or ErrorMessage), or a Message
        object, or None (if intermediate chunk is received)
        """
        ...
    


