"""
This type stub file was generated by pyright.
"""

import asyncua
from typing import List, Optional
from asyncua import ua

_logger = ...
async def copy_node(parent: asyncua.Node, node: asyncua.Node, nodeid: Optional[ua.NodeId] = ..., recursive: bool = ...) -> List[asyncua.Node]:
    """
    Copy a node or node tree as child of parent node
    """
    ...

