"""
This type stub file was generated by pyright.
"""

from typing import List, TYPE_CHECKING
from asyncua.common.node import Node

if TYPE_CHECKING:
    ...
_BROWSE_MASK = ...
class Event:
    """
    OPC UA Event object.
    This is class in inherited by the common event objects such as BaseEvent,
    other auto standard events and custom events
    Events are used to trigger events on server side and are
    sent to clients for every events from server

    Developer Warning:
    On server side the data type of attributes should be known, thus
    add properties using the add_property method!!!
    """
    def __init__(self, emitting_node=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def add_property(self, name, val, datatype): # -> None:
        """
        Add a property to event and store its data type
        """
        ...
    
    def add_variable(self, name, val, datatype): # -> None:
        """
        Add a variable to event and store its data type
        variables are able to have properties as children
        """
        ...
    
    def get_event_props_as_fields_dict(self): # -> dict[Any, Any]:
        """
        convert all properties and variables of the Event class to a dict of variants
        """
        ...
    
    @staticmethod
    def from_field_dict(fields): # -> Event:
        """
        Create an Event object from a dict of name and variants
        """
        ...
    
    def to_event_fields_using_subscription_fields(self, select_clauses): # -> list[Any]:
        """
        Using a new select_clauses and the original select_clauses
        used during subscription, return a field list
        """
        ...
    
    def to_event_fields(self, select_clauses): # -> list[Any]:
        """
        return a field list using a select clause and the object properties
        """
        ...
    
    @staticmethod
    def from_event_fields(select_clauses, fields): # -> Event:
        """
        Instantiate an Event object from a select_clauses and fields
        """
        ...
    
    @staticmethod
    def browse_path_to_attribute_name(browsePath):
        ...
    


async def get_filter_from_event_type(eventtypes: List[Node], where_clause_generation: bool = ...): # -> EventFilter:
    ...

async def select_clauses_from_evtype(evtypes: List[Node]): # -> list[Any]:
    ...

async def where_clause_from_evtype(evtypes: List[Node]): # -> ContentFilter:
    ...

async def select_event_attributes_from_type_node(node: Node, attributeSelector): # -> list[Any] | None:
    ...

async def get_event_properties_from_type_node(node: Node) -> List[Node]:
    ...

async def get_event_variables_from_type_node(node: Node) -> List[Node]:
    ...

async def get_event_objects_from_type_node(node: Node) -> List[Node]:
    ...

async def get_event_obj_from_type_node(node): # -> CustomEvent:
    """
    return an Event object from an event type node
    """
    class CustomEvent(parent_eventtype):
        ...
    
    

