"""
This type stub file was generated by pyright.
"""

import asyncua
from typing import List, Optional, Union
from asyncua import ua

"""
Instantiate a new node and its child nodes from a node type.
"""
_logger = ...
async def is_abstract(node_type) -> bool:
    ...

async def instantiate(parent: asyncua.Node, node_type: asyncua.Node, nodeid: Optional[ua.NodeId] = ..., bname: Optional[Union[ua.QualifiedName, str]] = ..., dname: Optional[ua.LocalizedText] = ..., idx: int = ..., instantiate_optional: bool = ...) -> List[asyncua.Node]:
    """
    instantiate a node type under a parent node.
    nodeid and browse name of new node can be specified, or just namespace index
    If they exists children of the node type, such as components, variables and
    properties are also instantiated
    """
    ...

