"""
This type stub file was generated by pyright.
"""

import asyncua
from typing import Any, Iterable, List, Optional, Tuple, Union
from asyncua import ua
from asyncua.common.session_interface import AbstractSession

"""
High level functions to create nodes
"""
_logger = ...
async def create_folder(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str]) -> asyncua.Node:
    """
    create a child node folder
    arguments are nodeid, browsename
    or namespace index, name
    """
    ...

async def create_object(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], objecttype: Optional[Union[ua.NodeId, int]] = ..., instantiate_optional: bool = ...) -> asyncua.Node:
    """
    create a child node object
    arguments are nodeid, browsename, [objecttype]
    or namespace index, name, [objecttype]
    if objectype is given (a NodeId) then the type node is instantiated inclusive its child nodes
    """
    ...

async def create_property(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], val: Any, varianttype: Optional[ua.VariantType] = ..., datatype: Optional[Union[ua.NodeId, int]] = ...) -> asyncua.Node:
    """
    create a child node property
    args are nodeid, browsename, value, [variant type]
    or idx, name, value, [variant type]
    """
    ...

async def create_variable(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], val: Any, varianttype: Optional[ua.VariantType] = ..., datatype: Optional[Union[ua.NodeId, int]] = ...) -> asyncua.Node:
    """
    create a child node variable
    args are nodeid, browsename, value, [variant type], [data type]
    or idx, name, value, [variant type], [data type]
    """
    ...

async def create_variable_type(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], datatype: Union[ua.NodeId, int]) -> asyncua.Node:
    """
    Create a new variable type
    args are nodeid, browsename and datatype
    or idx, name and data type
    """
    ...

async def create_reference_type(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str, int], symmetric: bool = ..., inversename: Optional[str] = ...) -> asyncua.Node:
    """
    Create a new reference type
    args are nodeid and browsename
    or idx and name
    """
    ...

async def create_object_type(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str]): # -> Node:
    """
    Create a new object type to be instantiated in address space.
    arguments are nodeid, browsename
    or namespace index, name
    """
    ...

async def create_method(parent: asyncua.Node, *args) -> asyncua.Node:
    """
    create a child method object
    This is only possible on server side!!
    args are nodeid, browsename, method_to_be_called, [input argument types], [output argument types]
    or idx, name, method_to_be_called, [input argument types], [output argument types]
    if argument types is specified, child nodes advertising what arguments the method uses and returns will be created
    a callback is a method accepting the nodeid of the parent as first argument and variants after.
    returns a list of variants
    """
    ...

async def create_data_type(parent: asyncua.Node, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], description: Optional[str] = ...) -> asyncua.Node:
    """
    Create a new data type to be used in new variables, etc ..
    arguments are nodeid, browsename
    or namespace index, name
    """
    ...

async def create_encoding(parent, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str]) -> asyncua.Node:
    """
    Create a new encoding object to be instantiated in address space.
    arguments are nodeid, browsename
    or namespace index, name
    """
    ...

async def delete_nodes(session: AbstractSession, nodes: Iterable[asyncua.Node], recursive: bool = ..., delete_target_references: bool = ...) -> Tuple[List[asyncua.Node], List[ua.StatusCode]]:
    """
    Delete specified nodes. Optionally delete recursively all nodes with a
    downward hierachic references to the node
    return the list of deleted node and the result
    """
    ...

