"""
This type stub file was generated by pyright.
"""

import asyncua
from typing import Any, Iterable, List, Union
from asyncua import ua

"""
High level method related functions
"""
async def call_method(parent: asyncua.Node, methodid: Union[ua.NodeId, ua.QualifiedName, str], *args) -> Any:
    """
    Call an OPC-UA method. methodid is browse name of child method or the
    nodeid of method as a NodeId object
    arguments are variants or python object convertible to variants.
    which may be of different types
    returns a list of values or a single value depending on the output of the method
    : param: parent `Node`
    """
    ...

async def call_method_full(parent: asyncua.Node, methodid: Union[ua.NodeId, ua.QualifiedName, str], *args) -> ua.CallMethodResult:
    """
    Call an OPC-UA method. methodid is browse name of child method or the
    nodeid of method as a NodeId object
    arguments are variants or python object convertible to variants.
    which may be of different types
    returns a CallMethodResult object with converted OutputArguments
    : param: parent `Node`
    """
    ...

def uamethod(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, list[Any] | CallMethodResult | StatusCode | List[Variant]]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], list[Any] | CallMethodResult | StatusCode | List[Variant]]:
    """
    Method decorator to automatically convert
    arguments and output to and from variants
    """
    ...

def to_variant(*args: Iterable) -> List[ua.Variant]:
    """Create a list of ua.Variants from a given iterable of arguments."""
    ...

