"""
This type stub file was generated by pyright.
"""

import sys
from datetime import datetime
from typing import Any, Iterable, List, Literal, Optional, Set, Union, overload
from asyncua import ua
from asyncua.common.session_interface import AbstractSession
from .events import Event

"""
High level node object, to access node attribute
and browse address space
"""
if sys.version_info >= (3, 8):
    ...
else:
    ...
_logger = ...
class Node:
    """
    High level node object, to access node attribute,
    browse and populate address space.
    Node objects are useful as-is but they do not expose the entire
    OPC-UA protocol. Feel free to look at the code of this class and call
    directly UA services methods to optimize your code
    """
    def __init__(self, session: AbstractSession, nodeid: Union[Node, ua.NodeId, str, int]) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    async def read_browse_name(self) -> ua.QualifiedName:
        """
        Get browse name of a node. A browse name is a QualifiedName object
        composed of a string(name) and a namespace index.
        """
        ...
    
    async def read_display_name(self) -> ua.LocalizedText:
        """
        get DisplayName attribute of node
        """
        ...
    
    async def read_data_type(self) -> ua.NodeId:
        """
        get data type of node as NodeId
        """
        ...
    
    async def read_data_type_as_variant_type(self) -> ua.VariantType:
        """
        get data type of node as VariantType
        This only works if node is a variable, otherwise type
        may not be convertible to VariantType
        """
        ...
    
    async def get_access_level(self) -> Set[ua.AccessLevel]:
        """
        Get the access level attribute of the node as a set of AccessLevel enum values.
        """
        ...
    
    async def get_user_access_level(self) -> Set[ua.AccessLevel]:
        """
        Get the user access level attribute of the node as a set of AccessLevel enum values.
        """
        ...
    
    async def read_event_notifier(self) -> Set[ua.EventNotifier]:
        """
        Get the event notifier attribute of the node as a set of EventNotifier enum values.
        """
        ...
    
    async def set_event_notifier(self, values) -> None:
        """
        Set the event notifier attribute.

        :param values: an iterable of EventNotifier enum values.
        """
        ...
    
    async def read_node_class(self) -> ua.NodeClass:
        """
        get node class attribute of node
        """
        ...
    
    async def read_data_type_definition(self) -> ua.DataTypeDefinition:
        """
        read data type definition attribute of node
        only DataType nodes following spec >= 1.04 have that attribute
        """
        ...
    
    async def write_data_type_definition(self, sdef: ua.DataTypeDefinition) -> None:
        """
        write data type definition attribute of node
        only DataType nodes following spec >= 1.04 have that attribute
        """
        ...
    
    async def read_description(self) -> ua.LocalizedText:
        """
        get description attribute class of node
        """
        ...
    
    async def read_value(self) -> Any:
        """
        Get value of a node as a python type. Only variables ( and properties) have values.
        An exception will be generated for other node types.
        WARNING: on server side, this function returns a ref to object in ua database.
        Do not modify it if it is a mutable object unless you know what you are doing
        """
        ...
    
    get_value = ...
    async def read_data_value(self, raise_on_bad_status: bool = ...) -> ua.DataValue:
        """
        Get value of a node as a DataValue object. Only variables (and properties) have values.
        An exception will be generated for other node types.
        DataValue contain a variable value as a variant as well as server and source timestamps
        """
        ...
    
    async def write_array_dimensions(self, value: int) -> None:
        """
        Set attribute ArrayDimensions of node
        make sure it has the correct data type
        """
        ...
    
    async def read_array_dimensions(self) -> List[int]:
        """
        Read and return ArrayDimensions attribute of node
        """
        ...
    
    async def write_value_rank(self, value: int) -> None:
        """
        Set attribute ValueRank of node
        """
        ...
    
    async def read_value_rank(self) -> int:
        """
        Read and return ValueRank attribute of node
        """
        ...
    
    async def write_value(self, value: Any, varianttype: Optional[ua.VariantType] = ...) -> None:
        """
        Write value of a node. Only variables(properties) have values.
        An exception will be generated for other node types.
        value argument is either:
        * a python built-in type, converted to opc-ua
        optionally using the variantype argument.
        * a ua.Variant, varianttype is then ignored
        * a ua.DataValue, you then have full control over data send to server
        WARNING: On server side, ref to object is directly saved in our UA db, if this is a mutable object
        and you modify it afterward, then the object in db will be modified without any
        data change event generated
        """
        ...
    
    set_data_value = ...
    set_value = ...
    async def set_writable(self, writable: bool = ...) -> None:
        """
        Set node as writable by clients.
        A node is always writable on server side.
        """
        ...
    
    async def set_attr_bit(self, attr: ua.AttributeIds, bit: int) -> None:
        ...
    
    async def unset_attr_bit(self, attr: ua.AttributeIds, bit: int) -> None:
        ...
    
    async def set_read_only(self) -> None:
        """
        Set a node as read-only for clients.
        A node is always writable on server side.
        """
        ...
    
    async def write_attribute(self, attributeid: ua.AttributeIds, datavalue: ua.DataValue, indexrange: Optional[str] = ...) -> None:
        """
        Set an attribute of a node
        attributeid is a member of ua.AttributeIds
        datavalue is a ua.DataValue object
        indexrange is a NumericRange (a string; e.g. "1" or "1:3".
            See https://reference.opcfoundation.org/v104/Core/docs/Part4/7.22/)
        """
        ...
    
    async def write_params(self, params: ua.WriteParameters) -> List[ua.StatusCode]:
        ...
    
    async def read_attribute(self, attr: ua.AttributeIds, indexrange: Optional[str] = ..., raise_on_bad_status: bool = ...) -> ua.DataValue:
        """
        Read one attribute of a node
        attributeid is a member of ua.AttributeIds
        indexrange is a NumericRange (a string; e.g. "1" or "1:3".
        result code from server is checked and an exception is raised in case of error
        """
        ...
    
    async def read_attributes(self, attrs: Iterable[ua.AttributeIds]) -> List[ua.DataValue]:
        """
        Read several attributes of a node
        list of DataValue is returned
        """
        ...
    
    async def read_params(self, params: ua.ReadParameters) -> List[ua.DataValue]:
        ...
    
    async def get_children(self, refs: int = ..., nodeclassmask: ua.NodeClass = ...) -> List[Node]:
        """
        Get all children of a node. By default hierarchical references and all node classes are returned.
        Other reference types may be given:
        References = 31
        NonHierarchicalReferences = 32
        HierarchicalReferences = 33
        HasChild = 34
        Organizes = 35
        HasEventSource = 36
        HasModellingRule = 37
        HasEncoding = 38
        HasDescription = 39
        HasTypeDefinition = 40
        GeneratesEvent = 41
        Aggregates = 44
        HasSubtype = 45
        HasProperty = 46
        HasComponent = 47
        HasNotifier = 48
        HasOrderedComponent = 49
        """
        ...
    
    async def get_properties(self) -> List[Node]:
        """
        return properties of node.
        properties are child nodes with a reference of type HasProperty and a NodeClass of Variable
        COROUTINE
        """
        ...
    
    async def get_variables(self) -> List[Node]:
        """
        return variables of node.
        variables are child nodes with a reference of type HasComponent and a NodeClass of Variable
        """
        ...
    
    async def get_methods(self) -> List[Node]:
        """
        return methods of node.
        methods are child nodes with a reference of type HasComponent and a NodeClass of Method
        """
        ...
    
    async def get_children_descriptions(self, refs: int = ..., nodeclassmask: ua.NodeClass = ..., includesubtypes: bool = ..., result_mask: ua.BrowseResultMask = ...) -> List[ua.ReferenceDescription]:
        ...
    
    async def get_encoding_refs(self) -> List[Node]:
        ...
    
    async def get_description_refs(self) -> List[Node]:
        ...
    
    async def get_references(self, refs: int = ..., direction: ua.BrowseDirection = ..., nodeclassmask: ua.NodeClass = ..., includesubtypes: bool = ..., result_mask: ua.BrowseResultMask = ...) -> List[ua.ReferenceDescription]:
        """
        returns references of the node based on specific filter defined with:

        refs = ObjectId of the Reference
        direction = Browse direction for references
        nodeclassmask = filter nodes based on specific class
        includesubtypes = If true subtypes of the reference (ref) are also included
        result_mask = define what results information are requested
        """
        ...
    
    async def get_referenced_nodes(self, refs: int = ..., direction: ua.BrowseDirection = ..., nodeclassmask: ua.NodeClass = ..., includesubtypes: bool = ...) -> List[Node]:
        """
        returns referenced nodes based on specific filter
        Parameters are the same as for get_references

        """
        ...
    
    async def read_type_definition(self) -> Optional[ua.NodeId]:
        """
        returns type definition of the node.
        """
        ...
    
    @overload
    async def get_path(self, max_length: int = ..., as_string: Literal[False] = ...) -> List[Node]:
        ...
    
    @overload
    async def get_path(self, max_length: int = ..., as_string: Literal[True] = ...) -> List[str]:
        ...
    
    async def get_path(self, max_length: int = ..., as_string: bool = ...) -> Union[List[Node], List[str]]:
        """
        Attempt to find path of node from root node and return it as a list of Nodes.
        There might several possible paths to a node, this function will return one
        Some nodes may be missing references, so this method may
        return an empty list
        Since address space may have circular references, a max length is specified
        """
        ...
    
    async def get_parent(self) -> Optional[Node]:
        """
        returns parent of the node.
        A Node may have several parents, the first found is returned.
        This method uses reverse references, a node might be missing such a link,
        thus we will not find its parent.
        """
        ...
    
    @overload
    async def get_child(self, path: Union[ua.QualifiedName, str, Iterable[Union[ua.QualifiedName, str]]], return_all: Literal[False] = ...) -> Node:
        ...
    
    @overload
    async def get_child(self, path: Union[ua.QualifiedName, str, Iterable[Union[ua.QualifiedName, str]]], return_all: Literal[True] = ...) -> List[Node]:
        ...
    
    async def get_child(self, path: Union[ua.QualifiedName, str, Iterable[Union[ua.QualifiedName, str]]], return_all: bool = ...) -> Union[Node, List[Node]]:
        """
        get a child specified by its path from this node.
        A path might be:
        * a string representing a relative path as per UA spec
        * a qualified name
        * a list of string representing browsenames (legacy)
        * a list of qualified names
        """
        ...
    
    async def get_children_by_path(self, paths: Iterable[Union[ua.QualifiedName, str, Iterable[Union[ua.QualifiedName, str]]]], raise_on_partial_error: bool = ...) -> List[List[Optional[Node]]]:
        """
        get children specified by their paths from this node.
        A path might be:
        * a string representing a relative path as per UA spec
        * a qualified name
        * a list of string representing browsenames (legacy)
        * a list of qualified names
        """
        ...
    
    async def read_raw_history(self, starttime: Optional[datetime] = ..., endtime: Optional[datetime] = ..., numvalues: int = ..., return_bounds: bool = ...) -> List[ua.DataValue]:
        """
        Read raw history of a node
        result code from server is checked and an exception is raised in case of error
        If numvalues is > 0 and number of events in period is > numvalues
        then result will be truncated
        """
        ...
    
    async def history_read(self, details: ua.ReadRawModifiedDetails, continuation_point: Optional[bytes] = ...) -> ua.HistoryReadResult:
        """
        Read raw history of a node, low-level function
        result code from server is checked and an exception is raised in case of error
        """
        ...
    
    async def read_event_history(self, starttime: datetime = ..., endtime: datetime = ..., numvalues: int = ..., evtypes: Union[Node, ua.NodeId, str, int, Iterable[Union[Node, ua.NodeId, str, int]]] = ...) -> List[Event]:
        """
        Read event history of a source node
        result code from server is checked and an exception is raised in case of error
        If numvalues is > 0 and number of events in period is > numvalues
        then result will be truncated
        """
        ...
    
    async def history_read_events(self, details: Iterable[ua.ReadEventDetails]) -> ua.HistoryReadResult:
        """
        Read event history of a node, low-level function
        result code from server is checked and an exception is raised in case of error
        """
        ...
    
    async def delete(self, delete_references: bool = ..., recursive: bool = ...) -> List[Node]:
        """
        Delete node from address space
        """
        ...
    
    async def delete_reference(self, target: Union[Node, ua.NodeId, str, int], reftype: int, forward: bool = ..., bidirectional: bool = ...) -> None:
        """
        Delete given node's references from address space
        """
        ...
    
    async def add_reference(self, target: Union[Node, ua.NodeId, str, int], reftype: int, forward: bool = ..., bidirectional: bool = ...) -> None:
        """
        Add reference to node
        """
        ...
    
    async def set_modelling_rule(self, mandatory: bool) -> None:
        """
        Add a modelling rule reference to Node.
        When creating a new object type, its variable and child nodes will not
        be instantiated if they do not have modelling rule
        if mandatory is None, the modelling rule is removed
        """
        ...
    
    async def add_folder(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str]) -> Node:
        ...
    
    async def add_object(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], objecttype: Optional[Union[ua.NodeId, int]] = ..., instantiate_optional: bool = ...) -> Node:
        ...
    
    async def add_variable(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], val: Any, varianttype: Optional[ua.VariantType] = ..., datatype: Optional[Union[ua.NodeId, int]] = ...) -> Node:
        ...
    
    async def add_object_type(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str]) -> Node:
        ...
    
    async def add_variable_type(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], datatype: Union[ua.NodeId, int]) -> Node:
        ...
    
    async def add_data_type(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], description: Optional[str] = ...) -> Node:
        ...
    
    async def add_property(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], val: Any, varianttype: Optional[ua.VariantType] = ..., datatype: Optional[Union[ua.NodeId, int]] = ...) -> Node:
        ...
    
    async def add_method(self, *args) -> Node:
        ...
    
    async def add_reference_type(self, nodeid: Union[ua.NodeId, str, int], bname: Union[ua.QualifiedName, str], symmetric: bool = ..., inversename: Optional[str] = ...) -> Node:
        ...
    
    async def call_method(self, methodid: Union[ua.NodeId, ua.QualifiedName, str], *args) -> Any:
        ...
    
    async def register(self) -> None:
        """
        Register node for faster read and write access (if supported by server)
        Rmw: This call modifies the nodeid of the node, the original nodeid is
        available as node.basenodeid
        """
        ...
    
    async def unregister(self) -> None:
        ...
    
    @staticmethod
    def new_node(session, nodeid: ua.NodeId) -> Node:
        """
        Helper function to init nodes with out importing Node
        """
        ...
    


