"""
This type stub file was generated by pyright.
"""

"""
Support for custom structures in client and server
We only support a subset of features but should be enough
for custom structures
"""
_logger = ...
class EnumType:
    def __init__(self, name) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def get_code(self): # -> str:
        ...
    


class EnumeratedValue:
    def __init__(self, name, value) -> None:
        ...
    


class Struct:
    def __init__(self, name) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def get_code(self): # -> str:
        ...
    


class Field:
    def __init__(self, name) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class StructGenerator:
    def __init__(self) -> None:
        ...
    
    def make_model_from_string(self, xml): # -> None:
        ...
    
    def make_model_from_file(self, path): # -> None:
        ...
    
    def save_to_file(self, path, register=...): # -> None:
        ...
    
    def get_python_classes(self, env=...): # -> dict[str, Any]:
        ...
    
    def set_typeid(self, name, typeid): # -> None:
        ...
    


async def load_type_definitions(server, nodes=...): # -> tuple[list[Any], dict[Any, Any]]:
    """
    Download xml from given variable node defining custom structures.
    If no node is given, attempts to import variables from all nodes under
    "0:OPC Binary"
    the code is generated and imported on the fly. If you know the structures
    are not going to be modified it might be interesting to copy the generated files
    and include them in you code
    """
    ...

async def load_enums(server, env=..., force=...): # -> dict[str, Any]:
    """
    Read enumeration data types on server and generate python Enums in ua scope for them
    """
    ...

