"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Set, TYPE_CHECKING, Tuple, Union
from asyncua import Client, Node, Server, ua

if TYPE_CHECKING:
    ...
_logger = ...
def new_struct_field(name: str, dtype: Union[ua.NodeId, Node, ua.VariantType], array: bool = ..., optional: bool = ..., description: str = ...) -> ua.StructureField:
    """
    simple way to create a StructureField
    """
    ...

async def new_struct(server: Union[Server, Client], idx: Union[int, ua.NodeId], name: Union[int, ua.QualifiedName], fields: List[ua.StructureField], is_union: bool = ...) -> Tuple[Node, List[Node]]:
    """
    simple way to create a new structure
    return the created data type node and the list of encoding nodes
    """
    ...

def new_enum_field(name: str, description: str = ...) -> ua.EnumField:
    """
    simple way to create an EnumField
    """
    ...

async def new_enum(server: Union[Server, Client], idx: Union[int, ua.NodeId], name: Union[int, ua.QualifiedName], fields: List[Union[str, ua.EnumField]], option_set: bool = ...) -> Node:
    ...

def clean_name(name): # -> str:
    """
    Remove characters that might be present in  OPC UA structures
    but cannot be part of Python class names
    """
    ...

def get_default_value(uatype, enums=..., hack=..., optional=...): # -> LiteralString | str | Literal[b""]:
    ...

def make_structure_code(data_type, struct_name, sdef, log_error=...): # -> str:
    """
    given a StructureDefinition object, generate Python code
    """
    ...

class DataTypeSorter:
    dtype_index: Dict[ua.NodeId, DataTypeSorter] = ...
    referenced_dtypes: Set[ua.NodeId] = ...
    def __init__(self, data_type: ua.NodeId, name: str, desc: ua.ReferenceDescription, sdef: ua.StructureDefinition) -> None:
        ...
    
    def depends_on(self, other: DataTypeSorter): # -> bool:
        ...
    
    def __lt__(self, other: DataTypeSorter) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


async def load_custom_struct(node: Node) -> Any:
    ...

async def load_custom_struct_xml_import(node_id: ua.NodeId, attrs: ua.DataTypeAttributes): # -> Any:
    """
    This function is used to load custom structs from xmlimporter
    """
    ...

async def load_basetype_alias_xml_import(server, name, nodeid, parent_datatype_nid): # -> Any:
    """
    Insert alias for a datatype used for xml import
    """
    ...

def make_basetype_code(name, parent_datatype): # -> dict[Any, Any]:
    """
    alias basetypes
    """
    ...

async def load_data_type_definitions(server: Union[Server, Client], base_node: Node = ..., overwrite_existing=...) -> Dict:
    """
    Read DataTypeDefinition attribute on all Structure and Enumeration defined
    on server and generate Python objects in ua namespace to be used to talk with server
    """
    ...

def make_enum_code(name, edef, option_set): # -> str:
    """
    if node has a DataTypeDefinition attribute, generate enum code
    """
    ...

async def load_enums(server: Union[Server, Client], base_node: Node = ..., option_set: bool = ...) -> Dict:
    ...

async def load_enum_xml_import(node_id: ua.NodeId, attrs: ua.DataTypeAttributes, option_set: bool): # -> Any:
    """
    This function is used to load enums from xmlimporter
    """
    ...

