"""
This type stub file was generated by pyright.
"""

import sys
from typing import Any, Iterable, List, Optional, Protocol, TYPE_CHECKING, Union, overload
from asyncua import ua
from asyncua.client.ua_client import UaClient
from asyncua.server.internal_session import InternalSession
from .node import Node

"""
high level interface to subscriptions
"""
if sys.version_info >= (3, 8):
    ...
else:
    ...
if TYPE_CHECKING:
    ...
class SubscriptionItemData:
    """
    To store useful data from a monitored item.
    """
    def __init__(self) -> None:
        ...
    


class DataChangeNotif:
    """
    To be send to clients for every datachange notification from server.
    """
    def __init__(self, subscription_data: SubscriptionItemData, monitored_item: ua.MonitoredItemNotification) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class DataChangeNotificationHandler(Protocol):
    def datachange_notification(self, node: Node, val: Any, data: DataChangeNotif) -> None:
        """
        called for every datachange notification from server
        """
        ...
    


class EventNotificationHandler(Protocol):
    def event_notification(self, event: ua.EventNotificationList) -> None:
        """
        called for every event notification from server
        """
        ...
    


class StatusChangeNotificationHandler(Protocol):
    def status_change_notification(self, status: ua.StatusChangeNotification) -> None:
        """
        called for every status change notification from server
        """
        ...
    


class DataChangeNotificationHandlerAsync(Protocol):
    async def datachange_notification(self, node: Node, val: Any, data: DataChangeNotif) -> None:
        """
        called for every datachange notification from server
        """
        ...
    


class EventNotificationHandlerAsync(Protocol):
    async def event_notification(self, event: ua.EventNotificationList) -> None:
        """
        called for every event notification from server
        """
        ...
    


class StatusChangeNotificationHandlerAsync(Protocol):
    async def status_change_notification(self, status: ua.StatusChangeNotification) -> None:
        """
        called for every status change notification from server
        """
        ...
    


SubscriptionHandler = Union[DataChangeNotificationHandler, EventNotificationHandler, StatusChangeNotificationHandler, DataChangeNotificationHandlerAsync, EventNotificationHandlerAsync, StatusChangeNotificationHandlerAsync,]
class Subscription:
    """
    Subscription object returned by Server or Client objects.
    The object represent a subscription to an opc-ua server.
    This is a high level class, especially `subscribe_data_change` and `subscribe_events methods`.
    If more control is necessary look at code and/or use `create_monitored_items method`.
    :param server: `InternalSession` or `UaClient`
    """
    def __init__(self, server: Union[InternalSession, UaClient], params: ua.CreateSubscriptionParameters, handler: SubscriptionHandler) -> None:
        ...
    
    async def init(self) -> ua.CreateSubscriptionResult:
        ...
    
    async def update(self, params: ua.ModifySubscriptionParameters) -> ua.ModifySubscriptionResult:
        ...
    
    async def publish_callback(self, publish_result: ua.PublishResult) -> None:
        """
        Handle `PublishResult` callback.
        """
        ...
    
    async def delete(self) -> None:
        """
        Delete subscription on server. This is automatically done by Client and Server classes on exit.
        """
        ...
    
    @overload
    async def subscribe_data_change(self, nodes: Node, attr: ua.AttributeIds = ..., queuesize: int = ..., monitoring=..., sampling_interval: ua.Duration = ...) -> int:
        ...
    
    @overload
    async def subscribe_data_change(self, nodes: Union[Node, Iterable[Node]], attr: ua.AttributeIds = ..., queuesize: int = ..., monitoring=..., sampling_interval: ua.Duration = ...) -> List[Union[int, ua.StatusCode]]:
        ...
    
    async def subscribe_data_change(self, nodes: Union[Node, Iterable[Node]], attr: ua.AttributeIds = ..., queuesize: int = ..., monitoring=..., sampling_interval: ua.Duration = ...) -> Union[int, List[Union[int, ua.StatusCode]]]:
        """
        Subscribe to data change events of one or multiple nodes.
        The default attribute used for the subscription is `Value`.
        Return value is a handle which can be used to modify/cancel the subscription.
        The handle is an integer value for single Nodes. If the creation of the subscription fails an
        `UaStatusCodeError` is raised.
        If multiple Nodes are supplied, a List of integers or ua.StatusCode objects is returned. A list of
        StatusCode objects are returned to indicate that the subscription has failed (no exception will be
        raised in this case).
        If more control is necessary the `create_monitored_items` method can be used directly.

        :param nodes: One Node or an Iterable of Nodes
        :param attr: The Node attribute you want to subscribe to
        :param queuesize: 0 or 1 for default queue size (shall be 1 - no queuing), n for FIFO queue
        :param sampling_interval: ua.Duration
        :return: Handle for changing/cancelling of the subscription
        """
        ...
    
    async def subscribe_events(self, sourcenode: Union[Node, ua.NodeId, str, int] = ..., evtypes: Union[Node, ua.NodeId, str, int, Iterable[Union[Node, ua.NodeId, str, int]]] = ..., evfilter: Optional[ua.EventFilter] = ..., queuesize: int = ..., where_clause_generation: bool = ...) -> int:
        """
        Subscribe to events from a node. Default node is Server node.
        In most servers the server node is the only one you can subscribe to.
        If evtypes is not provided, evtype defaults to BaseEventType.
        If evtypes is a list or tuple of custom event types, the events will be filtered to the supplied types.
        A handle (integer value) is returned which can be used to modify/cancel the subscription.

        :param sourcenode: int, str, ua.NodeId or Node
        :param evtypes: ua.ObjectIds, str, ua.NodeId or Node
        :param evfilter: ua.EventFilter which provides the SelectClauses and WhereClause
        :param queuesize: 0 for default queue size, 1 for minimum queue size, n for FIFO queue,
        MaxUInt32 for max queue size
        :param where_clause_generation: No where_clause generation when no eventfilter is provided. Need for TwinCAT, Codesys
        :return: Handle for changing/cancelling of the subscription
        """
        ...
    
    async def subscribe_alarms_and_conditions(self, sourcenode: Union[Node, ua.NodeId, str, int] = ..., evtypes: Union[Node, ua.NodeId, str, int, Iterable[Union[Node, ua.NodeId, str, int]]] = ..., evfilter: Optional[ua.EventFilter] = ..., queuesize: int = ...) -> int:
        """
        Subscribe to alarm and condition events from a node. Default node is Server node.
        In many servers the server node is the only one you can subscribe to.
        If evtypes is not provided, evtype defaults to ConditionType.
        If evtypes is a list or tuple of custom event types, the events will be filtered to the supplied types.
        A handle (integer value) is returned which can be used to modify/cancel the subscription.

        :param sourcenode: int, str, ua.NodeId or Node
        :param evtypes: ua.ObjectIds, str, ua.NodeId or Node
        :param evfilter: ua.EventFilter which provides the SelectClauses and WhereClause
        :param queuesize: 0 for default queue size, 1 for minimum queue size, n for FIFO queue,
        MaxUInt32 for max queue size
        :return: Handle for changing/cancelling of the subscription
        """
        ...
    
    async def create_monitored_items(self, monitored_items: Iterable[ua.MonitoredItemCreateRequest]) -> List[Union[int, ua.StatusCode]]:
        """
        low level method to have full control over subscription parameters.
        Client handle must be unique since it will be used as key for internal registration of data.
        """
        ...
    
    async def unsubscribe(self, handle: Union[int, Iterable[int]]) -> None:
        """
        Unsubscribe from datachange or events using the handle returned while subscribing.
        If you delete the subscription, you do not need to unsubscribe.
        :param handle: The handle that was returned when subscribing to the node/nodes
        """
        ...
    
    async def modify_monitored_item(self, handle: int, new_samp_time: ua.Duration, new_queuesize: int = ..., mod_filter_val: int = ...) -> List[ua.MonitoredItemModifyResult]:
        """
        Modify a monitored item.
        :param handle: Handle returned when originally subscribing
        :param new_samp_time: New wanted sample time
        :param new_queuesize: New wanted queuesize, default is 0
        :param mod_filter_val: New deadband filter value
        :return: Return a Modify Monitored Item Result
        """
        ...
    
    @overload
    async def deadband_monitor(self, var: Node, deadband_val: ua.Double, deadbandtype: ua.UInt32 = ..., queuesize: int = ..., attr: ua.AttributeIds = ...) -> int:
        ...
    
    @overload
    async def deadband_monitor(self, var: Iterable[Node], deadband_val: ua.Double, deadbandtype: ua.UInt32 = ..., queuesize: int = ..., attr: ua.AttributeIds = ...) -> List[Union[int, ua.StatusCode]]:
        ...
    
    async def deadband_monitor(self, var: Union[Node, Iterable[Node]], deadband_val: ua.Double, deadbandtype: ua.UInt32 = ..., queuesize: int = ..., attr: ua.AttributeIds = ...) -> Union[int, List[Union[int, ua.StatusCode]]]:
        """
        Method to create a subscription with a Deadband Value.
        Default deadband value type is absolute.
        Return a handle which can be used to unsubscribe
        :param var: Variable to which you want to subscribe
        :param deadband_val: Absolute float value
        :param deadbandtype: Default value is 1 (absolute), change to 2 for percentage deadband
        :param queuesize: Wanted queue size, default is 1
        :param attr: Attribute ID
        """
        ...
    
    async def set_monitoring_mode(self, monitoring: ua.MonitoringMode) -> List[ua.uatypes.StatusCode]:
        """
        The monitoring mode parameter is used
        to enable/disable the sampling of MonitoredItems
        (Samples don't queue on the server side)

        :param monitoring: The monitoring mode to apply
        :return: Return a Set Monitoring Mode Result
        """
        ...
    
    async def set_publishing_mode(self, publishing: bool) -> List[ua.uatypes.StatusCode]:
        """
        Disable publishing of NotificationMessages for the subscription,
        but doesn't discontinue the sending of keep-alive Messages,
        nor change the monitoring mode.

        :param publishing: The publishing mode to apply
        :return: Return a Set Publishing Mode Result
        """
        ...
    


