"""
This type stub file was generated by pyright.
"""

_logger = ...
_ua_build_in_types = ...
class OPCTypeDictionaryBuilder:
    def __init__(self, ns_urn) -> None:
        """
        :param ns_urn: name of the name space
        types in dict is created as opc:xxx, otherwise as tns:xxx
        """
        ...
    
    def add_field(self, type_name, variable_name, struct_name, is_array=...): # -> None:
        ...
    
    def append_struct(self, name): # -> Element[str]:
        ...
    
    def get_dict_value(self):
        ...
    
    def indent(self, elem, level=...): # -> None:
        ...
    


class DataTypeDictionaryBuilder:
    def __init__(self, server, idx, ns_urn, dict_name, dict_node_id=...) -> None:
        ...
    
    async def init(self): # -> None:
        ...
    
    async def create_data_type(self, type_name, nodeid=..., init=...): # -> StructNode:
        ...
    
    def add_field(self, type_name, variable_name, struct_name, is_array=...): # -> None:
        ...
    
    async def set_dict_byte_string(self): # -> None:
        ...
    


class StructNode:
    def __init__(self, type_dict, data_type, name, node_ids) -> None:
        ...
    
    def add_field(self, type_name, field_name, is_array=...): # -> None:
        ...
    


def get_ua_class(ua_class_name): # -> Any:
    ...

