"""
This type stub file was generated by pyright.
"""

"""
Useful methods and classes not belonging anywhere and depending on asyncua library
"""
_logger = ...
def value_to_datavalue(val, varianttype=...): # -> DataValue:
    """
    convert anything to a DataValue using varianttype
    """
    ...

def val_to_string(val, truncate=...): # -> LiteralString | str | String | None:
    """
    convert a python object or python-asyncua object to a string
    which should be easy to understand for human
    easy to modify, and not too hard to parse back ....not easy
    meant for UI or command lines
    if truncate is true then huge strings or bytes are truncated

    """
    ...

def variant_to_string(var): # -> LiteralString | str | String | None:
    """
    convert a variant to a string which should be easy to understand for human
    easy to modify, and not too hard to parse back ....not easy
    meant for UI or command lines
    """
    ...

def string_to_val(string, vtype): # -> list[Any] | bool | int | float | XmlElement | ExpandedNodeId | NodeId | QualifiedName | datetime | LocalizedText | StatusCode | UUID | Enum | None:
    """
    Convert back a string to a python or python-asyncua object
    Note: no error checking is done here, supplying null strings could raise exceptions (datetime and guid)
    """
    ...

def string_to_variant(string, vtype): # -> Variant:
    """
    convert back a string to an ua.Variant
    """
    ...

async def get_node_children(node, nodes=...): # -> list[Any]:
    """
    Get recursively all children of a node
    """
    ...

async def get_node_subtypes(node, nodes=...): # -> list[Any]:
    ...

async def get_node_supertypes(node, includeitself=..., skipbase=...): # -> list[Any]:
    """
    return get all subtype parents of node recursive
    :param node: can be an ua.Node or ua.NodeId
    :param includeitself: include also node to the list
    :param skipbase don't include the toplevel one
    :returns list of ua.Node, top parent first
    """
    ...

async def get_node_supertype(node): # -> None:
    """
    return node supertype or None
    """
    ...

async def is_subtype(node, supertype): # -> bool:
    """
    return if a node is a subtype of a specified nodeid
    """
    ...

async def is_child_present(node, browsename): # -> bool:
    """
    return if a browsename is present a child from the provide node
    :param node: node wherein to find the browsename
    :param browsename: browsename to search
    :returns returns True if the browsename is present else False
    """
    ...

async def data_type_to_variant_type(dtype_node): # -> VariantType:
    """
    Given a Node datatype, find out the variant type to encode
    data. This is not exactly straightforward...
    """
    ...

async def get_base_data_type(datatype):
    """
    Looks up the base datatype of the provided datatype Node
    The base datatype is either:
    A primitive type (ns=0, i<=21) or a complex one (ns=0 i>21 and i<30) like Enum and Struct.

    Args:
        datatype: NodeId of a datype of a variable
    Returns:
        NodeId of datatype base or None in case base datype can not be determined
    """
    ...

async def get_nodes_of_namespace(server, namespaces=...): # -> list[Any]:
    """
    Get the nodes of one or more namespaces .
    Args:
        server: opc ua server to use
        namespaces: list of string uri or int indexes of the namespace to export
    Returns:
        List of nodes that are part of the provided namespaces
    """
    ...

def get_default_value(uatype): # -> float | datetime | UUID | NodeId | ExpandedNodeId | StatusCode | QualifiedName | LocalizedText | ExtensionObject | DataValue | Variant | Any | Literal[False, 0, b""] | None:
    ...

def data_type_to_string(dtype):
    ...

def copy_dataclass_attr(dc_source, dc_dest) -> None:
    """
    Copy the common attributes of dc_source to dc_dest
    """
    ...

