"""
This type stub file was generated by pyright.
"""

from dataclasses import Field
from typing import Any, Awaitable, Dict, Optional, Tuple, TypeVar, Union
from ..ua.uaerrors import UaError

"""
Helper function and classes that do not rely on asyncua library.
Helper function and classes depending on ua object are in ua_utils.py
"""
_logger = ...
class ServiceError(UaError):
    def __init__(self, code) -> None:
        ...
    


class NotEnoughData(UaError):
    ...


class SocketClosedException(UaError):
    ...


class Buffer:
    """
    Alternative to io.BytesIO making debug easier
    and added a few convenience methods.
    """
    def __init__(self, data, start_pos=..., size=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def __len__(self): # -> int:
        ...
    
    def __bool__(self): # -> bool:
        ...
    
    def __bytes__(self): # -> bytes:
        """Return remains of buffer as bytes."""
        ...
    
    def read(self, size):
        """
        read and pop number of bytes for buffer
        """
        ...
    
    def copy(self, size=...): # -> Buffer:
        """
        return a shadow copy, optionally only copy 'size' bytes
        """
        ...
    
    def skip(self, size): # -> None:
        """
        skip size bytes in buffer
        """
        ...
    
    @property
    def cur_pos(self): # -> int:
        ...
    
    def rewind(self, cur_pos=...): # -> None:
        """
        rewind the buffer
        """
        ...
    


def create_nonce(size=...): # -> bytes:
    ...

def fields_with_resolved_types(class_or_instance: Any, globalns: Optional[Dict[str, Any]] = ..., localns: Optional[Dict[str, Any]] = ..., include_extras: bool = ...) -> Tuple[Field, ...]:
    """Return a tuple describing the fields of this dataclass.

    Accepts a dataclass or an instance of one. Tuple elements are of
    type Field. ForwardRefs and string types will be resolved.
    """
    ...

_T = TypeVar("_T")
async def wait_for(aw: Awaitable[_T], timeout: Union[int, float, None]) -> _T:
    """
    Wrapped version of asyncio.wait_for that does not swallow cancellations

    There is a bug in asyncio.wait_for before Python version 3.12 that prevents the inner awaitable from being cancelled
    when the task is cancelled from the outside.

    See https://github.com/python/cpython/issues/87555 and https://github.com/python/cpython/issues/86296
    """
    ...

