"""
This type stub file was generated by pyright.
"""

import asyncua
from typing import Union

"""
from a list of nodes in the address space, build an XML file
format is the one from opc-ua specification
"""
class XmlExporter:
    """
    If it is required that for _extobj_to_etree members to the value should be written in a certain
    order it can be added to the dictionary below.
    """
    extobj_ordered_elements = ...
    def __init__(self, server: Union[asyncua.Server, asyncua.Client], export_values: bool = ...) -> None:
        """
        param: export_values: exports values from variants (CustomDataTypes are not support!)
        """
        ...
    
    async def build_etree(self, node_list, add_all_namespaces=...): # -> None:
        """
        Create an XML etree object from a list of nodes;
        Namespaces used by nodes are always exported for consistency.
        Args:
            node_list: list of Node objects for export
            add_all_namespaces: if true export all server namespaces no matter which are used.
        Returns:
        """
        ...
    
    async def build_etree_chunked(self, node_list, add_all_namespaces=..., chunk_size=...): # -> None:
        """
        Create an XML etree object from a list of nodes in chunks to prevent a server-overload because of the mass requests;
        Namespaces used by nodes are always exported for consistency.
        Args:
            node_list: list of Node objects for export
            add_all_namespaces: if true export all server namespaces no matter which are used.
        Returns:
        """
        ...
    
    async def write_xml(self, xmlpath, pretty=...): # -> None:
        """
        Write the XML etree in the exporter object to a file
        Args:
            xmlpath: string representing the path/file name
            pretty: add spaces and newlines, to be more readable
        Returns:
        """
        ...
    
    def dump_etree(self): # -> None:
        """
        Dump etree to console for debugging
        Returns:
        """
        ...
    
    async def node_to_etree(self, node): # -> None:
        """
        Add the necessary XML sub elements to the etree for exporting the node
        Args:
            node: Node object which will be added to XML etree

        Returns:
        """
        ...
    
    async def add_etree_object(self, node): # -> None:
        """
        Add a UA object element to the XML etree
        """
        ...
    
    async def add_etree_object_type(self, node): # -> None:
        """
        Add a UA object type element to the XML etree
        """
        ...
    
    async def add_variable_common(self, node, el, export_value: bool): # -> None:
        ...
    
    async def add_etree_variable(self, node): # -> None:
        """
        Add a UA variable element to the XML etree
        """
        ...
    
    async def add_etree_variable_type(self, node): # -> None:
        """
        Add a UA variable type element to the XML etree
        """
        ...
    
    async def add_etree_method(self, node): # -> None:
        ...
    
    async def add_etree_reference_type(self, obj): # -> None:
        ...
    
    async def add_etree_datatype(self, obj): # -> None:
        """
        Add a UA data type element to the XML etree
        """
        ...
    
    async def member_to_etree(self, el, name, dtype, val): # -> None:
        ...
    
    async def value_to_etree(self, el, dtype_name, dtype, node): # -> None:
        ...
    


def indent(elem, level=...): # -> None:
    """
    copy and paste from http://effbot.org/zone/element-lib.htm#prettyprint
    it basically walks your tree and adds spaces and newlines so the tree is
    printed in a nice way
    """
    ...

