"""
This type stub file was generated by pyright.
"""

import asyncua
from typing import Union

"""
add nodes defined in XML to address space
format is the one from opc-ua specification
"""
_logger = ...
class XmlImporter:
    def __init__(self, server: Union[asyncua.Server, asyncua.Client], strict_mode: bool = ..., auto_load_definitions: bool = ...) -> None:
        """
        strict_mode: stop on an error, if False only an error message is logged,
                     but the import continues
        auto_load_definitions: auto generate code stubs on the fly for enum and structs
        """
        ...
    
    async def import_xml(self, xmlpath=..., xmlstring=...): # -> list[Any]:
        """
        import xml and return added nodes
        """
        ...
    
    def make_objects(self, node_data): # -> list[Any]:
        ...
    
    async def add_object(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    
    async def add_object_type(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    
    async def add_variable(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    
    async def add_variable_type(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    
    async def add_method(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    
    async def add_reference_type(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    
    async def add_datatype(self, obj, no_namespace_migration=...): # -> NodeId:
        ...
    


