"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple
from asyncua import ua

"""
parse xml file from asyncua-spec
"""
def ua_type_to_python(val, uatype_as_str): # -> list[Any] | bool | int | float | XmlElement | ExpandedNodeId | NodeId | QualifiedName | datetime | LocalizedText | StatusCode | UUID | Enum | None:
    """
    Converts a string value to a python value according to ua_utils.
    """
    ...

class NodeData:
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class Field:
    def __init__(self, data) -> None:
        ...
    


class RefStruct:
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class ExtObj:
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class XMLParser:
    def __init__(self) -> None:
        ...
    
    async def parse(self, xmlpath=..., xmlstring=...): # -> None:
        ...
    
    def parse_sync(self, xmlpath=..., xmlstring=...): # -> None:
        ...
    
    def get_used_namespaces(self): # -> list[str | None]:
        """
        Return the used namespace uris in this import file
        """
        ...
    
    def get_aliases(self) -> dict:
        """
        Return the used node aliases in this import file
        """
        ...
    
    def get_node_datas(self): # -> list[Any]:
        ...
    
    @staticmethod
    def list_required_models(xmlpath, xmlstring): # -> list[Any]:
        """
        Try getting required XML Models, before parsing NodeSet
        """
        ...
    
    def get_nodeset_namespaces(self) -> List[Tuple[str, ua.String, ua.DateTime]]:
        """
        Get all namespaces that are registered with version and date_time
        """
        ...
    


