"""
This type stub file was generated by pyright.
"""

import sys
from importlib import metadata
from .common import Node, uamethod
from .client import Client
from .server import Server

"""
Pure Python OPC-UA library
"""
if sys.version_info >= (3, 8):
    ...
else:
    ...
__version__ = ...
