"""
This type stub file was generated by pyright.
"""

class PostponeReferences:
    def __init__(self, server) -> None:
        ...
    
    def add_nodes(self, nodes): # -> None:
        ...
    
    def add_references(self, refs): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


def fill_address_space(nodeservice): # -> None:
    ...

