"""
This type stub file was generated by pyright.
"""

"""
DO NOT EDIT THIS FILE!
It is automatically generated from opcfoundation.org schemas.
Model Uri:http://opcfoundation.org/UA/
Version:1.05.04
Publication date:2025-01-08T00:00:00Z

File creation Date:2025-03-31 11:51:53.541082+00:00
"""
def create_standard_address_space_Services(server):
    ...

