"""
This type stub file was generated by pyright.
"""

import functools
from io import BytesIO
from typing import Any, Callable, IO, Optional, Sequence, Type, TypeVar, Union
from asyncua import ua
from ..common.utils import Buffer

"""
Binary protocol specific functions and constants
"""
_logger = ...
T = TypeVar("T")
def test_bit(data: int, offset: int) -> int:
    ...

def set_bit(data: int, offset: int) -> int:
    ...

def unset_bit(data: int, offset: int) -> int:
    ...

class _DateTime:
    @staticmethod
    def pack(dt): # -> bytes:
        ...
    
    @staticmethod
    def unpack(data): # -> datetime:
        ...
    


class _Bytes:
    @staticmethod
    def pack(data): # -> bytes:
        ...
    
    @staticmethod
    def unpack(data): # -> None:
        ...
    


class _String:
    @staticmethod
    def pack(string): # -> bytes:
        ...
    
    @staticmethod
    def unpack(data): # -> None:
        ...
    


class _Null:
    @staticmethod
    def pack(data): # -> Literal[b""]:
        ...
    
    @staticmethod
    def unpack(data): # -> None:
        ...
    


class _Guid:
    @staticmethod
    def pack(guid): # -> bytes:
        ...
    
    @staticmethod
    def unpack(data): # -> UUID:
        ...
    


class _Primitive1:
    def __init__(self, fmt) -> None:
        ...
    
    def pack(self, data): # -> bytes:
        ...
    
    def unpack(self, data): # -> Any:
        ...
    
    def pack_array(self, data): # -> bytes:
        ...
    
    def unpack_array(self, data, length): # -> tuple[()] | tuple[Any, ...] | None:
        ...
    


class Primitives1:
    SByte = ...
    Int16 = ...
    Int32 = ...
    Int64 = ...
    Byte = ...
    Char = ...
    UInt16 = ...
    UInt32 = ...
    UInt64 = ...
    Boolean = ...
    Double = ...
    Float = ...


class Primitives(Primitives1):
    Null = ...
    String = ...
    Bytes = ...
    ByteString = ...
    CharArray = ...
    DateTime = ...
    Guid = ...


@functools.lru_cache(maxsize=None)
def create_uatype_serializer(vtype): # -> Any | Callable[..., bytes | Any] | Callable[..., bytes] | Callable[..., bytearray | bytes | Any]:
    ...

def pack_uatype(vtype, value): # -> bytearray | bytes | Any:
    ...

def unpack_uatype(vtype, data): # -> NodeId | ExpandedNodeId | ExtensionObject | Enum | IntFlag | Variant | Any | None:
    ...

@functools.lru_cache(maxsize=None)
def create_uatype_array_serializer(vtype): # -> Any | Callable[..., bytes]:
    ...

def pack_uatype_array(vtype, array): # -> bytes | Any:
    ...

def unpack_uatype_array(vtype, data): # -> list[NodeId | ExpandedNodeId | ExtensionObject | Any | Enum | IntFlag | None] | None:
    ...

def field_serializer(ftype, dataclazz) -> Callable[[Any], bytes]:
    ...

@functools.lru_cache(maxsize=None)
def create_dataclass_serializer(dataclazz): # -> Callable[..., bytes]:
    """Given a dataclass, return a function that serializes instances of this dataclass"""
    ...

def struct_to_binary(obj): # -> bytes:
    ...

def create_enum_serializer(uatype): # -> Any | Callable[..., bytes]:
    ...

@functools.lru_cache(maxsize=None)
def create_type_serializer(uatype): # -> Callable[..., bytes] | Callable[[Sequence[Any] | None], bytes] | Any | Callable[..., bytes | Any] | Callable[..., bytearray | bytes | Any]:
    """Create a binary serialization function for the given UA type"""
    ...

def to_binary(uatype, val): # -> bytes | bytearray | Any:
    ...

@functools.lru_cache(maxsize=None)
def create_list_serializer(uatype, recursive: bool = ...) -> Callable[[Optional[Sequence[Any]]], bytes]:
    """
    Given a type, return a function that takes a list of instances
    of that type and serializes it.
    """
    ...

def list_to_binary(uatype, val): # -> bytes:
    ...

def nodeid_to_binary(nodeid): # -> bytearray | bytes:
    ...

def nodeid_from_binary(data: Union[BytesIO, Buffer]) -> Union[ua.NodeId, ua.ExpandedNodeId]:
    ...

def variant_to_binary(var): # -> bytes | Any:
    ...

def variant_from_binary(data): # -> Variant:
    ...

def extensionobject_from_binary(data: Buffer) -> ua.ExtensionObject:
    """
    Convert binary-coded ExtensionObject to a Python object.
    Returns an object, or None if TypeId is zero
    """
    ...

def extensionobject_to_binary(obj): # -> bytes:
    """
    Convert Python object to binary-coded ExtensionObject.
    If obj is None, convert to empty ExtensionObject (TypeId=0, no Body).
    Returns a binary string
    """
    ...

def create_enum_deserializer(uatype): # -> Callable[..., IntFlag] | Callable[..., Any]:
    ...

def from_binary(uatype, data): # -> NodeId | ExpandedNodeId | ExtensionObject | list[NodeId | ExpandedNodeId | ExtensionObject | Any | Enum | IntFlag | None] | Enum | IntFlag | Any | None:
    """
    unpack data given an uatype as a string or a python dataclass using ua types
    """
    ...

def struct_from_binary(objtype: Union[Type[T], str], data: IO) -> T:
    """
    unpack an ua struct. Arguments are an objtype as Python dataclass or string
    """
    ...

def header_to_binary(hdr): # -> bytes:
    ...

def header_from_binary(data): # -> Header:
    ...

def uatcp_to_binary(message_type, message): # -> bytes:
    """
    Convert OPC UA TCP message (see OPC UA specs Part 6, 7.1) to binary.
    The only supported types are Hello, Acknowledge and ErrorMessage
    """
    ...

