from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any
from urllib.parse import ParseResult

from asyncua import ua
from asyncua.server.server import Server
from asyncua.sync import SyncNode
from asyncua.ua.attribute_ids import AttributeIds
from common.node import Node
from common.subscription import Subscription, SubscriptionHandler
from crypto import security_policies, uacrypto
from cryptography import x509

_logger = ...

class Client:
    _username: str | None = ...
    _password: str | None = ...
    strip_url_credentials: bool = ...
    def __init__(self, url: str, timeout: float = ..., watchdog_intervall: float = ...) -> None: ...

    __repr__ = ...
    @property
    def server_url(self) -> ParseResult: ...
    @staticmethod
    def find_endpoint(
        endpoints: Iterable[ua.EndpointDescription],
        security_mode: ua.MessageSecurityMode,
        policy_uri: str,
    ) -> ua.EndpointDescription: ...
    def set_user(self, username: str) -> None: ...
    def set_password(self, pwd: str) -> None: ...
    def set_locale(self, locale: Sequence[str]) -> None: ...
    async def set_security_string(self, string: str) -> None: ...
    async def set_security(
        self,
        policy: type[security_policies.SecurityPolicy],
        certificate: str | uacrypto.CertProperties | bytes | Path,
        private_key: str | uacrypto.CertProperties | bytes | Path,
        private_key_password: str | bytes | None = ...,
        server_certificate: str | uacrypto.CertProperties | bytes | None = ...,
        mode: ua.MessageSecurityMode = ...,
    ) -> None: ...
    async def load_client_certificate(self, path: str, extension: str | None = ...) -> None: ...
    async def load_private_key(
        self,
        path: Path,
        password: str | bytes | None = ...,
        extension: str | None = ...,
    ) -> None: ...
    async def connect_and_get_server_endpoints(self) -> list[ua.EndpointDescription]: ...
    async def connect_and_find_servers(self) -> list[ua.ApplicationDescription]: ...
    async def connect_and_find_servers_on_network(self) -> list[ua.FindServersOnNetworkResult]: ...
    async def connect(self) -> None: ...
    async def connect_sessionless(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def disconnect_sessionless(self) -> None: ...
    async def connect_socket(self) -> None: ...
    def disconnect_socket(self) -> None: ...
    async def send_hello(self) -> None: ...
    async def open_secure_channel(self, renew: bool = ...) -> None: ...
    async def close_secure_channel(self) -> None: ...
    async def get_endpoints(self) -> list[ua.EndpointDescription]: ...
    async def register_server(
        self,
        server: Server,
        discovery_configuration: ua.DiscoveryConfiguration | None = ...,
    ) -> None: ...
    async def unregister_server(
        self,
        server: Server,
        discovery_configuration: ua.DiscoveryConfiguration | None = ...,
    ) -> None: ...
    async def find_servers(self, uris: Iterable[str] | None = ...) -> list[ua.ApplicationDescription]: ...
    async def find_servers_on_network(self) -> list[ua.FindServersOnNetworkResult]: ...
    async def create_session(self) -> ua.CreateSessionResult: ...
    async def check_connection(self) -> None: ...
    def server_policy(self, token_type: ua.UserTokenType) -> ua.UserTokenPolicy: ...
    async def activate_session(
        self,
        username: str | None = ...,
        password: str | None = ...,
        certificate: x509.Certificate | None = ...,
    ) -> ua.ActivateSessionResult: ...
    async def close_session(self) -> None: ...
    def get_root_node(self) -> Node: ...
    def get_objects_node(self) -> Node: ...
    def get_server_node(self) -> Node: ...
    def get_node(self, nodeid: Node | ua.NodeId | str | int) -> Node: ...
    async def create_subscription(
        self,
        period: ua.CreateSubscriptionParameters | float,
        handler: SubscriptionHandler,
        publishing: bool = ...,
    ) -> Subscription: ...
    def get_subscription_revised_params(
        self,
        params: ua.CreateSubscriptionParameters,
        results: ua.CreateSubscriptionResult,
    ) -> ua.ModifySubscriptionParameters | None: ...
    async def delete_subscriptions(self, subscription_ids: Iterable[int]) -> list[ua.StatusCode]: ...
    def get_keepalive_count(self, period: float) -> int: ...
    async def get_namespace_array(self) -> list[str]: ...
    async def get_namespace_index(self, uri: str) -> int: ...
    async def delete_nodes(
        self,
        nodes: Iterable[Node],
        recursive: bool = ...,
    ) -> tuple[list[Node], list[ua.StatusCode]]: ...
    async def import_xml(
        self,
        path: str = ...,
        xmlstring: str = ...,
        strict_mode: bool = ...,
        auto_load_definitions: bool = ...,
    ) -> list[ua.NodeId]: ...
    async def export_xml(self, nodes: list[SyncNode], path: str, export_values: bool = ...) -> None: ...
    async def register_namespace(self, uri: str) -> int: ...
    async def load_type_definitions(self, nodes: list[SyncNode] = ...) -> None: ...
    async def load_data_type_definitions(
        self,
        node: Node | None = ...,
        overwrite_existing: bool = ...,
    ) -> dict[str, type]: ...
    async def load_enums(self) -> dict[str, type]: ...
    async def register_nodes(self, nodes: Iterable[Node]) -> list[Node]: ...
    async def unregister_nodes(self, nodes: Iterable[Node]) -> None: ...
    async def read_attributes(self, nodes: Iterable[Node], attr: AttributeIds = ...) -> list[ua.DataValue]: ...
    async def read_values(self, nodes: Iterable[Node]) -> list[Any]: ...
    async def write_values(
        self,
        nodes: Iterable[Node],
        values: Iterable[Any],
        raise_on_partial_error: bool = ...,
    ) -> list[ua.StatusCode]: ...

    get_values = ...
    set_values = ...
    async def browse_nodes(self, nodes: Iterable[Node]) -> list[tuple[Node, ua.BrowseResult]]: ...
    async def translate_browsepaths(
        self,
        starting_node: ua.NodeId,
        relative_paths: Iterable[ua.RelativePath | str],
    ) -> list[ua.BrowsePathResult]: ...
