"""
This type stub file was generated by pyright.
"""

from enum import Enum
from dataclasses import dataclass
from typing import Optional

ADMIN_TYPES = ...
USER_TYPES = ...
class UserRole(Enum):
    """
    User Roles
    """
    Admin = ...
    Anonymous = ...
    User = ...


@dataclass
class User:
    role: UserRole = ...
    name: Optional[str] = ...


class PermissionRuleset:
    """
    Base class for permission ruleset
    """
    def check_validity(self, user, action_type, body):
        ...
    


class SimpleRoleRuleset(PermissionRuleset):
    """
    Standard simple role-based ruleset.
    Admins alone can change address space, admins and users can read/write, and anonymous users can't do anything.
    """
    def __init__(self) -> None:
        ...
    
    def check_validity(self, user, action_type_id, body): # -> bool:
        ...
    


