"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING
from abc import ABCMeta, abstractmethod
from ..ua import MessageSecurityMode
from ..crypto.permission_rules import PermissionRuleset

if TYPE_CHECKING:
    ...
_logger = ...
class Signer:
    """
    Abstract base class for cryptographic signature algorithm
    """
    __metaclass__ = ABCMeta
    @abstractmethod
    def signature_size(self): # -> None:
        ...
    
    @abstractmethod
    def signature(self, data): # -> None:
        ...
    


class Verifier:
    """
    Abstract base class for cryptographic signature verification
    """
    __metaclass__ = ABCMeta
    @abstractmethod
    def signature_size(self): # -> None:
        ...
    
    @abstractmethod
    def verify(self, data, signature): # -> None:
        ...
    
    def reset(self): # -> None:
        ...
    


class Encryptor:
    """
    Abstract base class for encryption algorithm
    """
    __metaclass__ = ABCMeta
    @abstractmethod
    def plain_block_size(self): # -> None:
        ...
    
    @abstractmethod
    def encrypted_block_size(self): # -> None:
        ...
    
    @abstractmethod
    def encrypt(self, data): # -> None:
        ...
    


class Decryptor:
    """
    Abstract base class for decryption algorithm
    """
    __metaclass__ = ABCMeta
    @abstractmethod
    def plain_block_size(self): # -> None:
        ...
    
    @abstractmethod
    def encrypted_block_size(self): # -> None:
        ...
    
    @abstractmethod
    def decrypt(self, data): # -> None:
        ...
    
    def reset(self): # -> None:
        ...
    


class CryptographyNone:
    """
    Base class for symmetric/asymmetric cryptography
    """
    def __init__(self) -> None:
        ...
    
    def plain_block_size(self): # -> Literal[1]:
        """
        Size of plain text block for block cipher.
        """
        ...
    
    def encrypted_block_size(self): # -> Literal[1]:
        """
        Size of encrypted text block for block cipher.
        """
        ...
    
    def padding(self, size): # -> Literal[b""]:
        """
        Create padding for a block of given size.
        plain_size = size + len(padding) + signature_size()
        plain_size = N * plain_block_size()
        """
        ...
    
    def min_padding_size(self): # -> Literal[0]:
        ...
    
    def signature_size(self): # -> Literal[0]:
        ...
    
    def signature(self, data): # -> Literal[b""]:
        ...
    
    def encrypt(self, data):
        ...
    
    def decrypt(self, data):
        ...
    
    def vsignature_size(self): # -> Literal[0]:
        ...
    
    def verify(self, data, signature): # -> None:
        """
        Verify signature and raise exception if signature is invalid
        """
        ...
    
    def remove_padding(self, data):
        ...
    


class Cryptography(CryptographyNone):
    """
    Security policy: Sign or SignAndEncrypt
    """
    def __init__(self, mode=...) -> None:
        ...
    
    def plain_block_size(self): # -> Literal[1]:
        """
        Size of plain text block for block cipher.
        """
        ...
    
    def encrypted_block_size(self): # -> Literal[1]:
        """
        Size of encrypted text block for block cipher.
        """
        ...
    
    def padding(self, size): # -> bytes:
        """
        Create padding for a block of given size.
        plain_size = size + len(padding) + signature_size()
        plain_size = N * plain_block_size()
        """
        ...
    
    def min_padding_size(self): # -> Literal[1, 0]:
        ...
    
    def signature_size(self):
        ...
    
    def signature(self, data):
        ...
    
    def vsignature_size(self):
        ...
    
    def verify(self, data, sig): # -> None:
        ...
    
    def encrypt(self, data):
        ...
    
    def decrypt(self, data):
        ...
    
    def revolved_expired_key(self): # -> None:
        """
        Remove expired keys as soon as possible
        """
        ...
    
    @property
    def use_prev_key(self): # -> bool:
        ...
    
    @use_prev_key.setter
    def use_prev_key(self, value: bool): # -> None:
        ...
    
    def remove_padding(self, data):
        ...
    


class SignerRsa(Signer):
    def __init__(self, host_privkey) -> None:
        ...
    
    def signature_size(self):
        ...
    
    def signature(self, data):
        ...
    


class VerifierRsa(Verifier):
    def __init__(self, peer_cert) -> None:
        ...
    
    def signature_size(self):
        ...
    
    def verify(self, data, signature): # -> None:
        ...
    


class EncryptorRsa(Encryptor):
    def __init__(self, peer_cert, enc_fn, padding_size) -> None:
        ...
    
    def plain_block_size(self):
        ...
    
    def encrypted_block_size(self):
        ...
    
    def encrypt(self, data): # -> Literal[b""]:
        ...
    


class DecryptorRsa(Decryptor):
    def __init__(self, host_privkey, dec_fn, padding_size) -> None:
        ...
    
    def plain_block_size(self):
        ...
    
    def encrypted_block_size(self):
        ...
    
    def decrypt(self, data): # -> Literal[b""]:
        ...
    


class SignerAesCbc(Signer):
    def __init__(self, key) -> None:
        ...
    
    def signature_size(self): # -> property:
        ...
    
    def signature(self, data): # -> bytes:
        ...
    


class VerifierAesCbc(Verifier):
    def __init__(self, key) -> None:
        ...
    
    def signature_size(self): # -> property:
        ...
    
    def verify(self, data, signature): # -> None:
        ...
    


class EncryptorAesCbc(Encryptor):
    def __init__(self, key, init_vec) -> None:
        ...
    
    def plain_block_size(self): # -> int:
        ...
    
    def encrypted_block_size(self): # -> int:
        ...
    
    def encrypt(self, data): # -> bytes:
        ...
    


class DecryptorAesCbc(Decryptor):
    def __init__(self, key, init_vec) -> None:
        ...
    
    def plain_block_size(self): # -> int:
        ...
    
    def encrypted_block_size(self): # -> int:
        ...
    
    def decrypt(self, data): # -> bytes:
        ...
    


class SignerSha256(Signer):
    def __init__(self, host_privkey) -> None:
        ...
    
    def signature_size(self):
        ...
    
    def signature(self, data):
        ...
    


class VerifierSha256(Verifier):
    def __init__(self, peer_cert) -> None:
        ...
    
    def signature_size(self):
        ...
    
    def verify(self, data, signature): # -> None:
        ...
    


class SignerHMac256(Signer):
    def __init__(self, key) -> None:
        ...
    
    def signature_size(self): # -> property:
        ...
    
    def signature(self, data): # -> bytes:
        ...
    


class VerifierHMac256(Verifier):
    def __init__(self, key) -> None:
        ...
    
    def signature_size(self): # -> property:
        ...
    
    def verify(self, data, signature): # -> None:
        ...
    


class SignerPssSha256(Signer):
    def __init__(self, host_privkey) -> None:
        ...
    
    def signature_size(self):
        ...
    
    def signature(self, data):
        ...
    


class VerifierPssSha256(Verifier):
    def __init__(self, peer_cert) -> None:
        ...
    
    def signature_size(self):
        ...
    
    def verify(self, data, signature): # -> None:
        ...
    


class SecurityPolicy:
    """
    Abstract base class for security policy
    """
    __metaclass__ = ABCMeta
    URI: str
    AsymmetricEncryptionURI: str
    AsymmetricSignatureURI: str
    secure_channel_nonce_length: int
    asymmetric_cryptography: CryptographyNone
    symmetric_cryptography: CryptographyNone
    Mode: MessageSecurityMode
    peer_certificate: Optional[bytes]
    host_certificate: Optional[bytes]
    permissions: Optional[PermissionRuleset]
    @abstractmethod
    def __init__(self, peer_cert, host_cert, host_privkey, mode, permission_ruleset=...) -> None:
        ...
    
    @abstractmethod
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    @abstractmethod
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


class SecurityPolicyNone(SecurityPolicy):
    URI = ...
    AsymmetricEncryptionURI: str = ...
    AsymmetricSignatureURI: str = ...
    secure_channel_nonce_length: int = ...
    def __init__(self, peer_cert=..., host_cert=..., host_privkey=..., mode=..., permission_ruleset=...) -> None:
        ...
    
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


class SecurityPolicyAes128Sha256RsaOaep(SecurityPolicy):
    """
    Security Aes128 Sha256 RsaOaep
    A suite of algorithms that uses Sha256 as Key-Wrap-algorithm
    and 128-Bit (16 bytes) for encryption algorithms.

    - SymmetricSignatureAlgorithm_HMAC-SHA2-256
      https://tools.ietf.org/html/rfc4634
    - SymmetricEncryptionAlgorithm_AES128-CBC
      http://www.w3.org/2001/04/xmlenc#aes256-cbc
    - AsymmetricSignatureAlgorithm_RSA-PKCS15-SHA2-256
      http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    - AsymmetricEncryptionAlgorithm_RSA-OAEP-SHA1
      http://www.w3.org/2001/04/xmlenc#rsa-oaep
    - KeyDerivationAlgorithm_P-SHA2-256
      http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512/dk/p_sha256
    - CertificateSignatureAlgorithm_RSA-PKCS15-SHA2-256
      http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    - Aes128Sha256RsaOaep_Limits
        -> DerivedSignatureKeyLength: 256 bits
        -> MinAsymmetricKeyLength: 2048 bits
        -> MaxAsymmetricKeyLength: 4096 bits
        -> SecureChannelNonceLength: 32 bytes
    """
    URI = ...
    AsymmetricEncryptionURI = ...
    AsymmetricSignatureURI = ...
    secure_channel_nonce_length = ...
    signature_key_size = ...
    symmetric_key_size = ...
    @staticmethod
    def encrypt_asymmetric(pubkey, data):
        ...
    
    @staticmethod
    def sign_asymmetric(privkey, data):
        ...
    
    def __init__(self, peer_cert, host_cert, host_privkey, mode, permission_ruleset=...) -> None:
        ...
    
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


class SecurityPolicyAes256Sha256RsaPss(SecurityPolicy):
    """Security policy Aes256_Sha256_RsaPss implementation

    - SymmetricSignatureAlgorithm_HMAC-SHA2-256
      https://tools.ietf.org/html/rfc4634
    - SymmetricEncryptionAlgorithm_AES256-CBC
      http://www.w3.org/2001/04/xmlenc#aes256-cbc
    - AsymmetricSignatureAlgorithm_RSA-PSS-SHA2-256
      http://opcfoundation.org/UA/security/rsa-pss-sha2-256
    - AsymmetricEncryptionAlgorithm_RSA-OAEP-SHA2-256
      http://opcfoundation.org/UA/security/rsa-oaep-sha2-256
    - KeyDerivationAlgorithm_P-SHA2-256
      http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512/dk/p_sha256
    - CertificateSignatureAlgorithm_RSA-PKCS15-SHA2-256
      http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    - Aes256Sha256RsaPss_Limits
        -> DerivedSignatureKeyLength: 256 bits
        -> MinAsymmetricKeyLength: 2048 bits
        -> MaxAsymmetricKeyLength: 4096 bits
        -> SecureChannelNonceLength: 32 bytes
    """
    URI = ...
    AsymmetricEncryptionURI = ...
    AsymmetricSignatureURI = ...
    secure_channel_nonce_length = ...
    signature_key_size = ...
    symmetric_key_size = ...
    @staticmethod
    def encrypt_asymmetric(pubkey, data):
        ...
    
    @staticmethod
    def sign_asymmetric(privkey, data):
        ...
    
    def __init__(self, peer_cert, host_cert, host_privkey, mode, permission_ruleset=...) -> None:
        ...
    
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


class SecurityPolicyBasic128Rsa15(SecurityPolicy):
    """
    DEPRECATED, do not use anymore!

    Security Basic 128Rsa15
    A suite of algorithms that uses RSA15 as Key-Wrap-algorithm
    and 128-Bit (16 bytes) for encryption algorithms.
    - SymmetricSignatureAlgorithm - HmacSha1
      (http://www.w3.org/2000/09/xmldsig#hmac-sha1)
    - SymmetricEncryptionAlgorithm - Aes128
      (http://www.w3.org/2001/04/xmlenc#aes128-cbc)
    - AsymmetricSignatureAlgorithm - RsaSha1
      (http://www.w3.org/2000/09/xmldsig#rsa-sha1)
    - AsymmetricKeyWrapAlgorithm - KwRsa15
      (http://www.w3.org/2001/04/xmlenc#rsa-1_5)
    - AsymmetricEncryptionAlgorithm - Rsa15
      (http://www.w3.org/2001/04/xmlenc#rsa-1_5)
    - KeyDerivationAlgorithm - PSha1
      (http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512/dk/p_sha1)
    - DerivedSignatureKeyLength - 128 (16 bytes)
    - MinAsymmetricKeyLength - 1024 (128 bytes)
    - MaxAsymmetricKeyLength - 2048 (256 bytes)
    - CertificateSignatureAlgorithm - Sha1

    If a certificate or any certificate in the chain is not signed with
    a hash that is Sha1 or stronger than the certificate shall be rejected.
    """
    URI = ...
    AsymmetricEncryptionURI = ...
    AsymmetricSignatureURI = ...
    secure_channel_nonce_length = ...
    signature_key_size = ...
    symmetric_key_size = ...
    @staticmethod
    def encrypt_asymmetric(pubkey, data):
        ...
    
    @staticmethod
    def sign_asymmetric(privkey, data):
        ...
    
    def __init__(self, peer_cert, host_cert, host_privkey, mode, permission_ruleset=...) -> None:
        ...
    
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


class SecurityPolicyBasic256(SecurityPolicy):
    """
    DEPRECATED, do not use anymore!

    Security Basic 256
    A suite of algorithms that are for 256-Bit (32 bytes) encryption,
    algorithms include:
    - SymmetricSignatureAlgorithm - HmacSha1
      (http://www.w3.org/2000/09/xmldsig#hmac-sha1)
    - SymmetricEncryptionAlgorithm - Aes256
      (http://www.w3.org/2001/04/xmlenc#aes256-cbc)
    - AsymmetricSignatureAlgorithm - RsaSha1
      (http://www.w3.org/2000/09/xmldsig#rsa-sha1)
    - AsymmetricKeyWrapAlgorithm - KwRsaOaep
      (http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p)
    - AsymmetricEncryptionAlgorithm - RsaOaep
      (http://www.w3.org/2001/04/xmlenc#rsa-oaep)
    - KeyDerivationAlgorithm - PSha1
      (http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512/dk/p_sha1)
    - DerivedSignatureKeyLength - 192 (24 bytes)
    - MinAsymmetricKeyLength - 1024 (128 bytes)
    - MaxAsymmetricKeyLength - 2048 (256 bytes)
    - CertificateSignatureAlgorithm - Sha1

    If a certificate or any certificate in the chain is not signed with
    a hash that is Sha1 or stronger than the certificate shall be rejected.
    """
    URI = ...
    AsymmetricEncryptionURI = ...
    AsymmetricSignatureURI = ...
    secure_channel_nonce_length = ...
    signature_key_size = ...
    symmetric_key_size = ...
    @staticmethod
    def encrypt_asymmetric(pubkey, data):
        ...
    
    @staticmethod
    def sign_asymmetric(privkey, data):
        ...
    
    def __init__(self, peer_cert, host_cert, host_privkey, mode, permission_ruleset=...) -> None:
        ...
    
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


class SecurityPolicyBasic256Sha256(SecurityPolicy):
    """
    Security Basic 256Sha256
    A suite of algorithms that uses Sha256 as Key-Wrap-algorithm
    and 256-Bit (32 bytes) for encryption algorithms.

    - SymmetricSignatureAlgorithm_HMAC-SHA2-256
      https://tools.ietf.org/html/rfc4634
    - SymmetricEncryptionAlgorithm_AES256-CBC
      http://www.w3.org/2001/04/xmlenc#aes256-cbc
    - AsymmetricSignatureAlgorithm_RSA-PKCS15-SHA2-256
      http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    - AsymmetricEncryptionAlgorithm_RSA-OAEP-SHA1
      http://www.w3.org/2001/04/xmlenc#rsa-oaep
    - KeyDerivationAlgorithm_P-SHA2-256
      http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512/dk/p_sha256
    - CertificateSignatureAlgorithm_RSA-PKCS15-SHA2-256
      http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    - Basic256Sha256_Limits
        -> DerivedSignatureKeyLength: 256 bits
        -> MinAsymmetricKeyLength: 2048 bits
        -> MaxAsymmetricKeyLength: 4096 bits
        -> SecureChannelNonceLength: 32 bytes
    """
    URI = ...
    AsymmetricEncryptionURI = ...
    AsymmetricSignatureURI = ...
    secure_channel_nonce_length = ...
    signature_key_size = ...
    symmetric_key_size = ...
    @staticmethod
    def encrypt_asymmetric(pubkey, data):
        ...
    
    @staticmethod
    def sign_asymmetric(privkey, data):
        ...
    
    def __init__(self, peer_cert, host_cert, host_privkey, mode, permission_ruleset=...) -> None:
        ...
    
    def make_local_symmetric_key(self, secret, seed): # -> None:
        ...
    
    def make_remote_symmetric_key(self, secret, seed, lifetime): # -> None:
        ...
    


def encrypt_asymmetric(pubkey, data, policy_uri): # -> tuple[Any, Any] | tuple[Any, Literal['']]:
    """
    Encrypt data with pubkey using an asymmetric algorithm.
    The algorithm is selected by policy_uri.
    Returns a tuple (encrypted_data, algorithm_uri)
    """
    ...

class SecurityPolicyFactory:
    """
    Helper class for creating server-side SecurityPolicy.
    Server has one certificate and private key, but needs a separate
    SecurityPolicy for every client and client's certificate
    """
    def __init__(self, cls, mode, certificate=..., private_key=..., permission_ruleset=...) -> None:
        ...
    
    def matches(self, uri, mode=...): # -> Literal[True]:
        ...
    
    def create(self, peer_certificate):
        ...
    


def sign_asymmetric(privkey, data, policy_uri): # -> tuple[Any, Any] | tuple[Any, Literal['']]:
    """
    Sign data with privkey using an asymmetric algorithm.
    The algorithm is selected by policy_uri.
    Returns a tuple (signature, algorithm_uri)
    """
    ...

SECURITY_POLICY_TYPE_MAP = ...
