"""
This type stub file was generated by pyright.
"""

from typing import List
from pathlib import Path
from cryptography import x509

"""
Functionality for checking a certificate based on:
- trusted (ca) certificates
- crl

Use of cryptography module is prefered, but  doesn't provide functionality for truststores yet, so for some we rely on using pyOpenSSL.

"""
_logger = ...
class TrustStore:
    """
    TrustStore is used to validate certificates in two ways:
    - Based on being absent in provided certificate revocation lists
    - The certificate or its issuer being  present in a list of trusted certificates

    It doesn't check other content of extensions of the certificate
    """
    def __init__(self, trust_locations: List[Path], crl_locations: List[Path]) -> None:
        """Constructor of the TrustStore

        Args:
            trust_locations (list[Path]): one or multiple locations that contain trusted (ca) certificates. Type should be DER.
            crl_locations (list[Path]): one or multiple locations that contain CRL. TYpe should be DER.
        """
        ...
    
    @property
    def trust_locations(self) -> List[Path]:
        ...
    
    @property
    def crl_locations(self) -> List[Path]:
        ...
    
    async def load(self): # -> None:
        """(re)load both the trusted certificates and revoctions lists"""
        ...
    
    async def load_trust(self): # -> None:
        """(re)load the trusted certificates"""
        ...
    
    async def load_crl(self): # -> None:
        """(re)load the certificate revocation lists"""
        ...
    
    def validate(self, certificate: x509.Certificate) -> bool:
        """Validates if a certificate is trusted, not revoked and lays in valid datarange

        Args:
            certificate (x509.Certificate): Certificate to check

        Returns:
            bool: Returns True when the certificate is valid
        """
        ...
    
    def check_date_range(self, certificate: x509.Certificate) -> bool:
        """Checks if the certificate not_valid_before_utc and not_valid_after_utc are valid.

        Args:
            certificate (x509.Certificate): Certificate to check

        Returns:
            bool: Returns True when the now lays in valid range of the certificate
        """
        ...
    
    def is_revoked(self, certificate: x509.Certificate) -> bool:
        """Check if the provided certifcate is in the revocation lists

        when not CRLs are present it the certificate is considere not revoked.

        Args:
            certificate (x509.Certificate): Certificate to check

        Returns:
            bool: True when it is on a revocation list. If no list is present also return False.
        """
        ...
    
    def is_trusted(self, certificate: x509.Certificate) -> bool:
        """Check if the provided certifcate is considered trusted
        For a self-signed to be trusted is must be placed in the trusted location
        Args:
            certificate (x509.Certificate): Certificate to check

        Returns:
            bool: True when it is trusted or the trust store is empty.
        """
        ...
    


