"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional, Union
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import rsa
from dataclasses import dataclass

_logger = ...
class InvalidSignature(Exception):
    ...


@dataclass
class CertProperties:
    path_or_content: Union[bytes, Path, str]
    extension: Optional[str] = ...
    password: Optional[Union[str, bytes]] = ...


async def get_content(path_or_content: Union[str, bytes, Path]) -> bytes:
    ...

async def load_certificate(path_or_content: Union[bytes, str, Path], extension: Optional[str] = ...): # -> Certificate:
    ...

def x509_from_der(data): # -> Certificate | None:
    """Load X.509 certificate from DER data.

    This function handles both single certificates and certificate chains.
    When a certificate chain is detected, it extracts and returns the first
    certificate in the chain.

    Args:
        data (bytes): DER-encoded certificate data

    Returns:
        x509.Certificate or None: Loaded certificate object or None if data is empty
    """
    ...

async def load_private_key(path_or_content: Union[str, Path, bytes], password: Optional[Union[str, bytes]] = ..., extension: Optional[str] = ...): # -> PrivateKeyTypes:
    ...

def der_from_x509(certificate): # -> Literal[b""]:
    ...

def pem_from_key(private_key: rsa.RSAPrivateKey) -> bytes:
    """dumps a private key in PEM format

    Args:
        private_key (rsa.RSAPrivateKey): The privatekey to dump

    Returns:
        bytes: The private as PEM/PKCS8 format
    """
    ...

def sign_sha1(private_key, data):
    ...

def sign_sha256(private_key, data):
    ...

def sign_pss_sha256(private_key, data):
    ...

def verify_sha1(certificate, data, signature): # -> None:
    ...

def verify_sha256(certificate, data, signature): # -> None:
    ...

def verify_pss_sha256(certificate, data, signature): # -> None:
    ...

def encrypt_basic256(public_key, data):
    ...

def encrypt_rsa_oaep(public_key, data):
    ...

def encrypt_rsa_oaep_sha256(public_key, data):
    ...

def encrypt_rsa15(public_key, data):
    ...

def decrypt_rsa_oaep(private_key, data):
    ...

def decrypt_rsa_oaep_sha256(private_key, data):
    ...

def decrypt_rsa15(private_key, data):
    ...

def cipher_aes_cbc(key, init_vec): # -> Cipher[CBC]:
    ...

def cipher_encrypt(cipher, data):
    ...

def cipher_decrypt(cipher, data):
    ...

def hmac_sha1(key, message): # -> bytes:
    ...

def hmac_sha256(key, message): # -> bytes:
    ...

def sha1_size(): # -> property:
    ...

def sha256_size(): # -> property:
    ...

def p_sha1(secret, seed, sizes=...): # -> tuple[Any, ...]:
    """
    Derive one or more keys from secret and seed.
    (See specs part 6, 6.7.5 and RFC 2246 - TLS v1.0)
    Lengths of keys will match sizes argument
    """
    ...

def p_sha256(secret, seed, sizes=...): # -> tuple[Any, ...]:
    """
    Derive one or more keys from secret and seed.
    (See specs part 6, 6.7.5 and RFC 2246 - TLS v1.0)
    Lengths of keys will match sizes argument
    """
    ...

def x509_name_to_string(name): # -> str:
    ...

def x509_to_string(cert): # -> str:
    """
    Convert x509 certificate to human-readable string
    """
    ...

def check_certificate(cert: x509.Certificate, application_uri: str, hostname: Optional[str] = ...) -> bool:
    """
    check certificate if it matches the application_uri and log errors.
    """
    ...

