"""
This type stub file was generated by pyright.
"""

from typing import Awaitable, Callable, Optional
from enum import Flag
from cryptography import x509
from asyncua import ua
from asyncua.ua import ApplicationDescription
from asyncua.crypto.truststore import TrustStore

_logger = ...
CertificateValidatorMethod = Callable[[x509.Certificate, ApplicationDescription], Awaitable[None]]
class CertificateValidatorOptions(Flag):
    """
    Flags for which certificate validation should be performed

    Three default sets of flags are provided:
    - BASIC_VALIDATION
    - EXT_VALIDATION
    - TRUSTED_VALIDATION
    """
    TIME_RANGE = ...
    URI = ...
    KEY_USAGE = ...
    EXT_KEY_USAGE = ...
    TRUSTED = ...
    REVOKED = ...
    PEER_CLIENT = ...
    PEER_SERVER = ...
    BASIC_VALIDATION = ...
    EXT_VALIDATION = ...
    TRUSTED_VALIDATION = ...


class CertificateValidator:
    """
    CertificateValidator contains a basic certificate validator including trusted store with revocation list support.
    The CertificateValidator can be used as a CertificateValidatorMethod.

    Default CertificateValidatorOptions.BASIC_VALIDATION is used.
    """
    def __init__(self, options: CertificateValidatorOptions = ..., trust_store: Optional[TrustStore] = ...) -> None:
        ...
    
    def set_validate_options(self, options: CertificateValidatorOptions): # -> None:
        """Change the use validation options at runtime"""
        ...
    
    async def validate(self, cert: x509.Certificate, app_description: ua.ApplicationDescription): # -> None:
        """Validate if a certificate is valid based on the validation options.
        When not valid is raises a ServiceError with an UA Result Code.

        Args:
            cert (x509.Certificate): certificate to check
            app_description (ua.ApplicationDescription): application descriptor of the client/server

        Raises:
            BadCertificateTimeInvalid: When current time is not in the time range of the certificate
            BadCertificateUriInvalid: Uri from certificate doesn't match application descriptor uri
            BadCertificateUseNotAllowed: KeyUsage or ExtendedKeyUsage fields mismatch
            BadCertificateInvalid: General when part of certifcate fields can't be found
            BadCertificateUntrusted: Not trusted by TrustStore
            ApplicationDescription: Certifacate in CRL of the TrustStore
        """
        ...
    
    async def __call__(self, cert: x509.Certificate, app_description: ua.ApplicationDescription): # -> None:
        ...
    


