"""
This type stub file was generated by pyright.
"""

from asyncua.ua.uaerrors import UaStatusCodeError

class Bad(UaStatusCodeError):
    code = ...


class BadUnexpectedError(UaStatusCodeError):
    code = ...


class BadInternalError(UaStatusCodeError):
    code = ...


class BadOutOfMemory(UaStatusCodeError):
    code = ...


class BadResourceUnavailable(UaStatusCodeError):
    code = ...


class BadCommunicationError(UaStatusCodeError):
    code = ...


class BadEncodingError(UaStatusCodeError):
    code = ...


class BadDecodingError(UaStatusCodeError):
    code = ...


class BadEncodingLimitsExceeded(UaStatusCodeError):
    code = ...


class BadRequestTooLarge(UaStatusCodeError):
    code = ...


class BadResponseTooLarge(UaStatusCodeError):
    code = ...


class BadUnknownResponse(UaStatusCodeError):
    code = ...


class BadTimeout(UaStatusCodeError):
    code = ...


class BadServiceUnsupported(UaStatusCodeError):
    code = ...


class BadShutdown(UaStatusCodeError):
    code = ...


class BadServerNotConnected(UaStatusCodeError):
    code = ...


class BadServerHalted(UaStatusCodeError):
    code = ...


class BadNothingToDo(UaStatusCodeError):
    code = ...


class BadTooManyOperations(UaStatusCodeError):
    code = ...


class BadTooManyMonitoredItems(UaStatusCodeError):
    code = ...


class BadDataTypeIdUnknown(UaStatusCodeError):
    code = ...


class BadCertificateInvalid(UaStatusCodeError):
    code = ...


class BadSecurityChecksFailed(UaStatusCodeError):
    code = ...


class BadCertificatePolicyCheckFailed(UaStatusCodeError):
    code = ...


class BadCertificateTimeInvalid(UaStatusCodeError):
    code = ...


class BadCertificateIssuerTimeInvalid(UaStatusCodeError):
    code = ...


class BadCertificateHostNameInvalid(UaStatusCodeError):
    code = ...


class BadCertificateUriInvalid(UaStatusCodeError):
    code = ...


class BadCertificateUseNotAllowed(UaStatusCodeError):
    code = ...


class BadCertificateIssuerUseNotAllowed(UaStatusCodeError):
    code = ...


class BadCertificateUntrusted(UaStatusCodeError):
    code = ...


class BadCertificateRevocationUnknown(UaStatusCodeError):
    code = ...


class BadCertificateIssuerRevocationUnknown(UaStatusCodeError):
    code = ...


class BadCertificateRevoked(UaStatusCodeError):
    code = ...


class BadCertificateIssuerRevoked(UaStatusCodeError):
    code = ...


class BadCertificateChainIncomplete(UaStatusCodeError):
    code = ...


class BadUserAccessDenied(UaStatusCodeError):
    code = ...


class BadIdentityTokenInvalid(UaStatusCodeError):
    code = ...


class BadIdentityTokenRejected(UaStatusCodeError):
    code = ...


class BadSecureChannelIdInvalid(UaStatusCodeError):
    code = ...


class BadInvalidTimestamp(UaStatusCodeError):
    code = ...


class BadNonceInvalid(UaStatusCodeError):
    code = ...


class BadSessionIdInvalid(UaStatusCodeError):
    code = ...


class BadSessionClosed(UaStatusCodeError):
    code = ...


class BadSessionNotActivated(UaStatusCodeError):
    code = ...


class BadSubscriptionIdInvalid(UaStatusCodeError):
    code = ...


class BadRequestHeaderInvalid(UaStatusCodeError):
    code = ...


class BadTimestampsToReturnInvalid(UaStatusCodeError):
    code = ...


class BadRequestCancelledByClient(UaStatusCodeError):
    code = ...


class BadTooManyArguments(UaStatusCodeError):
    code = ...


class BadLicenseExpired(UaStatusCodeError):
    code = ...


class BadLicenseLimitsExceeded(UaStatusCodeError):
    code = ...


class BadLicenseNotAvailable(UaStatusCodeError):
    code = ...


class BadServerTooBusy(UaStatusCodeError):
    code = ...


class BadNoCommunication(UaStatusCodeError):
    code = ...


class BadWaitingForInitialData(UaStatusCodeError):
    code = ...


class BadNodeIdInvalid(UaStatusCodeError):
    code = ...


class BadNodeIdUnknown(UaStatusCodeError):
    code = ...


class BadAttributeIdInvalid(UaStatusCodeError):
    code = ...


class BadIndexRangeInvalid(UaStatusCodeError):
    code = ...


class BadIndexRangeNoData(UaStatusCodeError):
    code = ...


class BadIndexRangeDataMismatch(UaStatusCodeError):
    code = ...


class BadDataEncodingInvalid(UaStatusCodeError):
    code = ...


class BadDataEncodingUnsupported(UaStatusCodeError):
    code = ...


class BadNotReadable(UaStatusCodeError):
    code = ...


class BadNotWritable(UaStatusCodeError):
    code = ...


class BadOutOfRange(UaStatusCodeError):
    code = ...


class BadNotSupported(UaStatusCodeError):
    code = ...


class BadNotFound(UaStatusCodeError):
    code = ...


class BadObjectDeleted(UaStatusCodeError):
    code = ...


class BadNotImplemented(UaStatusCodeError):
    code = ...


class BadMonitoringModeInvalid(UaStatusCodeError):
    code = ...


class BadMonitoredItemIdInvalid(UaStatusCodeError):
    code = ...


class BadMonitoredItemFilterInvalid(UaStatusCodeError):
    code = ...


class BadMonitoredItemFilterUnsupported(UaStatusCodeError):
    code = ...


class BadFilterNotAllowed(UaStatusCodeError):
    code = ...


class BadStructureMissing(UaStatusCodeError):
    code = ...


class BadEventFilterInvalid(UaStatusCodeError):
    code = ...


class BadContentFilterInvalid(UaStatusCodeError):
    code = ...


class BadFilterOperatorInvalid(UaStatusCodeError):
    code = ...


class BadFilterOperatorUnsupported(UaStatusCodeError):
    code = ...


class BadFilterOperandCountMismatch(UaStatusCodeError):
    code = ...


class BadFilterOperandInvalid(UaStatusCodeError):
    code = ...


class BadFilterElementInvalid(UaStatusCodeError):
    code = ...


class BadFilterLiteralInvalid(UaStatusCodeError):
    code = ...


class BadContinuationPointInvalid(UaStatusCodeError):
    code = ...


class BadNoContinuationPoints(UaStatusCodeError):
    code = ...


class BadReferenceTypeIdInvalid(UaStatusCodeError):
    code = ...


class BadBrowseDirectionInvalid(UaStatusCodeError):
    code = ...


class BadNodeNotInView(UaStatusCodeError):
    code = ...


class BadNumericOverflow(UaStatusCodeError):
    code = ...


class BadLocaleNotSupported(UaStatusCodeError):
    code = ...


class BadNoValue(UaStatusCodeError):
    code = ...


class BadServerUriInvalid(UaStatusCodeError):
    code = ...


class BadServerNameMissing(UaStatusCodeError):
    code = ...


class BadDiscoveryUrlMissing(UaStatusCodeError):
    code = ...


class BadSemaphoreFileMissing(UaStatusCodeError):
    code = ...


class BadRequestTypeInvalid(UaStatusCodeError):
    code = ...


class BadSecurityModeRejected(UaStatusCodeError):
    code = ...


class BadSecurityPolicyRejected(UaStatusCodeError):
    code = ...


class BadTooManySessions(UaStatusCodeError):
    code = ...


class BadUserSignatureInvalid(UaStatusCodeError):
    code = ...


class BadApplicationSignatureInvalid(UaStatusCodeError):
    code = ...


class BadNoValidCertificates(UaStatusCodeError):
    code = ...


class BadIdentityChangeNotSupported(UaStatusCodeError):
    code = ...


class BadRequestCancelledByRequest(UaStatusCodeError):
    code = ...


class BadParentNodeIdInvalid(UaStatusCodeError):
    code = ...


class BadReferenceNotAllowed(UaStatusCodeError):
    code = ...


class BadNodeIdRejected(UaStatusCodeError):
    code = ...


class BadNodeIdExists(UaStatusCodeError):
    code = ...


class BadNodeClassInvalid(UaStatusCodeError):
    code = ...


class BadBrowseNameInvalid(UaStatusCodeError):
    code = ...


class BadBrowseNameDuplicated(UaStatusCodeError):
    code = ...


class BadNodeAttributesInvalid(UaStatusCodeError):
    code = ...


class BadTypeDefinitionInvalid(UaStatusCodeError):
    code = ...


class BadSourceNodeIdInvalid(UaStatusCodeError):
    code = ...


class BadTargetNodeIdInvalid(UaStatusCodeError):
    code = ...


class BadDuplicateReferenceNotAllowed(UaStatusCodeError):
    code = ...


class BadInvalidSelfReference(UaStatusCodeError):
    code = ...


class BadReferenceLocalOnly(UaStatusCodeError):
    code = ...


class BadNoDeleteRights(UaStatusCodeError):
    code = ...


class BadServerIndexInvalid(UaStatusCodeError):
    code = ...


class BadViewIdUnknown(UaStatusCodeError):
    code = ...


class BadViewTimestampInvalid(UaStatusCodeError):
    code = ...


class BadViewParameterMismatch(UaStatusCodeError):
    code = ...


class BadViewVersionInvalid(UaStatusCodeError):
    code = ...


class BadNotTypeDefinition(UaStatusCodeError):
    code = ...


class BadTooManyMatches(UaStatusCodeError):
    code = ...


class BadQueryTooComplex(UaStatusCodeError):
    code = ...


class BadNoMatch(UaStatusCodeError):
    code = ...


class BadMaxAgeInvalid(UaStatusCodeError):
    code = ...


class BadSecurityModeInsufficient(UaStatusCodeError):
    code = ...


class BadHistoryOperationInvalid(UaStatusCodeError):
    code = ...


class BadHistoryOperationUnsupported(UaStatusCodeError):
    code = ...


class BadInvalidTimestampArgument(UaStatusCodeError):
    code = ...


class BadWriteNotSupported(UaStatusCodeError):
    code = ...


class BadTypeMismatch(UaStatusCodeError):
    code = ...


class BadMethodInvalid(UaStatusCodeError):
    code = ...


class BadArgumentsMissing(UaStatusCodeError):
    code = ...


class BadNotExecutable(UaStatusCodeError):
    code = ...


class BadTooManySubscriptions(UaStatusCodeError):
    code = ...


class BadTooManyPublishRequests(UaStatusCodeError):
    code = ...


class BadNoSubscription(UaStatusCodeError):
    code = ...


class BadSequenceNumberUnknown(UaStatusCodeError):
    code = ...


class BadMessageNotAvailable(UaStatusCodeError):
    code = ...


class BadInsufficientClientProfile(UaStatusCodeError):
    code = ...


class BadStateNotActive(UaStatusCodeError):
    code = ...


class BadAlreadyExists(UaStatusCodeError):
    code = ...


class BadTcpServerTooBusy(UaStatusCodeError):
    code = ...


class BadTcpMessageTypeInvalid(UaStatusCodeError):
    code = ...


class BadTcpSecureChannelUnknown(UaStatusCodeError):
    code = ...


class BadTcpMessageTooLarge(UaStatusCodeError):
    code = ...


class BadTcpNotEnoughResources(UaStatusCodeError):
    code = ...


class BadTcpInternalError(UaStatusCodeError):
    code = ...


class BadTcpEndpointUrlInvalid(UaStatusCodeError):
    code = ...


class BadRequestInterrupted(UaStatusCodeError):
    code = ...


class BadRequestTimeout(UaStatusCodeError):
    code = ...


class BadSecureChannelClosed(UaStatusCodeError):
    code = ...


class BadSecureChannelTokenUnknown(UaStatusCodeError):
    code = ...


class BadSequenceNumberInvalid(UaStatusCodeError):
    code = ...


class BadProtocolVersionUnsupported(UaStatusCodeError):
    code = ...


class BadConfigurationError(UaStatusCodeError):
    code = ...


class BadNotConnected(UaStatusCodeError):
    code = ...


class BadDeviceFailure(UaStatusCodeError):
    code = ...


class BadSensorFailure(UaStatusCodeError):
    code = ...


class BadOutOfService(UaStatusCodeError):
    code = ...


class BadDeadbandFilterInvalid(UaStatusCodeError):
    code = ...


class BadRefreshInProgress(UaStatusCodeError):
    code = ...


class BadConditionAlreadyDisabled(UaStatusCodeError):
    code = ...


class BadConditionAlreadyEnabled(UaStatusCodeError):
    code = ...


class BadConditionDisabled(UaStatusCodeError):
    code = ...


class BadEventIdUnknown(UaStatusCodeError):
    code = ...


class BadEventNotAcknowledgeable(UaStatusCodeError):
    code = ...


class BadDialogNotActive(UaStatusCodeError):
    code = ...


class BadDialogResponseInvalid(UaStatusCodeError):
    code = ...


class BadConditionBranchAlreadyAcked(UaStatusCodeError):
    code = ...


class BadConditionBranchAlreadyConfirmed(UaStatusCodeError):
    code = ...


class BadConditionAlreadyShelved(UaStatusCodeError):
    code = ...


class BadConditionNotShelved(UaStatusCodeError):
    code = ...


class BadShelvingTimeOutOfRange(UaStatusCodeError):
    code = ...


class BadNoData(UaStatusCodeError):
    code = ...


class BadBoundNotFound(UaStatusCodeError):
    code = ...


class BadBoundNotSupported(UaStatusCodeError):
    code = ...


class BadDataLost(UaStatusCodeError):
    code = ...


class BadDataUnavailable(UaStatusCodeError):
    code = ...


class BadEntryExists(UaStatusCodeError):
    code = ...


class BadNoEntryExists(UaStatusCodeError):
    code = ...


class BadTimestampNotSupported(UaStatusCodeError):
    code = ...


class BadAggregateListMismatch(UaStatusCodeError):
    code = ...


class BadAggregateNotSupported(UaStatusCodeError):
    code = ...


class BadAggregateInvalidInputs(UaStatusCodeError):
    code = ...


class BadAggregateConfigurationRejected(UaStatusCodeError):
    code = ...


class BadRequestNotAllowed(UaStatusCodeError):
    code = ...


class BadRequestNotComplete(UaStatusCodeError):
    code = ...


class BadTransactionPending(UaStatusCodeError):
    code = ...


class BadTicketRequired(UaStatusCodeError):
    code = ...


class BadTicketInvalid(UaStatusCodeError):
    code = ...


class BadLocked(UaStatusCodeError):
    code = ...


class BadRequiresLock(UaStatusCodeError):
    code = ...


class BadDominantValueChanged(UaStatusCodeError):
    code = ...


class BadDependentValueChanged(UaStatusCodeError):
    code = ...


class BadEdited_OutOfRange(UaStatusCodeError):
    code = ...


class BadInitialValue_OutOfRange(UaStatusCodeError):
    code = ...


class BadOutOfRange_DominantValueChanged(UaStatusCodeError):
    code = ...


class BadEdited_OutOfRange_DominantValueChanged(UaStatusCodeError):
    code = ...


class BadOutOfRange_DominantValueChanged_DependentValueChanged(UaStatusCodeError):
    code = ...


class BadEdited_OutOfRange_DominantValueChanged_DependentValueChanged(UaStatusCodeError):
    code = ...


class BadInvalidArgument(UaStatusCodeError):
    code = ...


class BadConnectionRejected(UaStatusCodeError):
    code = ...


class BadDisconnect(UaStatusCodeError):
    code = ...


class BadConnectionClosed(UaStatusCodeError):
    code = ...


class BadInvalidState(UaStatusCodeError):
    code = ...


class BadEndOfStream(UaStatusCodeError):
    code = ...


class BadNoDataAvailable(UaStatusCodeError):
    code = ...


class BadWaitingForResponse(UaStatusCodeError):
    code = ...


class BadOperationAbandoned(UaStatusCodeError):
    code = ...


class BadExpectedStreamToBlock(UaStatusCodeError):
    code = ...


class BadWouldBlock(UaStatusCodeError):
    code = ...


class BadSyntaxError(UaStatusCodeError):
    code = ...


class BadMaxConnectionsReached(UaStatusCodeError):
    code = ...


class BadDataSetIdInvalid(UaStatusCodeError):
    code = ...


