"""
This type stub file was generated by pyright.
"""

"""
Define exceptions to be raised at various places in the stack
"""
class UaError(RuntimeError):
    ...


class UaStatusCodeError(UaError):
    """
    This exception is raised when a bad status code is encountered.

    It exposes the status code number in the `code' property, so the
    user can distinguish between the different status codes and maybe
    handle some of them.

    The list of status error codes can be found in asyncua.ua.status_codes.
    """
    _subclasses = ...
    @classmethod
    def __init_subclass__(cls): # -> None:
        ...
    
    def __new__(cls, *args): # -> Self:
        """
        Creates a new UaStatusCodeError but returns a more specific subclass
        if possible, e.g.

            UaStatusCodeError(0x80010000) => BadUnexpectedError()
        """
        ...
    
    def __init__(self, code=...) -> None:
        """
        :param code: The code of the exception. Only needed when not instanciating
                     a concrete subclass such as BadInternalError.
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def code(self): # -> Any:
        """
        The code of the status error.
        """
        ...
    


class UaStatusCodeErrors(UaStatusCodeError):
    def __new__(cls, *args): # -> Self:
        ...
    
    def __init__(self, codes) -> None:
        """
        :param codes: The codes of the results.
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def code(self): # -> None:
        """
        The code of the status error.
        """
        ...
    


class UaStringParsingError(UaError):
    ...


class UaStructParsingError(UaError):
    ...


class UaInvalidParameterError(UaError):
    ...


